"""
The hand-made part of the wiki: the pages that aren't one registry entry (minigames, stories, mechanics, dimensions), the
links between things that the game data doesn't spell out, and where the knowledge-base chunks of the one-page wiki go.

Everything here is small tables. The texts themselves come from tools/make_wiki.py (the knowledge base), the lists from
the game data; a new variant, item, block, structure, biome, clothing piece, NPC or critter gets its page without any
change here (and turns up in the "unassigned" part of the report if the knowledge base has text for it that has no home).
"""

# --- dimensions ------------------------------------------------------------------------------------------------------------
# id -> (NL name, EN name, picture, NL lead, EN lead)
DIMENSIONS = {
    "guhmension": ("De Guhmensie", "The Guhmension", "guh_portal",
                   "De roze wereld van de guhs: wol, kaassaus, guhkristallen en bijna alle bouwwerken, minigames en verhalen. Je komt er via een portaal van blokken kaasknabbels.",
                   "The pink world of the guhs: wool, cheese sauce, guh crystals and almost every structure, minigame and story. You get there through a portal of blocks of kaasknabbels."),
    "guhmaag": ("De Guhmaag", "The Guh stomach", "maag_portal",
                "Je eigen kamer in de buik van Moeder Vadsig: een zachte roze maag die je kunt inrichten en laten groeien. Je krijgt het buikfluitje na haar quest.",
                "Your own room in Mother Vadsig's belly: a soft pink stomach you can furnish and make bigger. You get the belly whistle after her quest."),
    "guheinde": ("Het Guheinde", "The Guheinde", "structure_guheinde_knabbelberg",
                 "Het eindspel van Guhs: een eiland van kaaskorst in het niets, waar Opper-Mika op de hongerige Enderguh alle kaasknabbels bewaakt.",
                 "The endgame of Guhs: an island of cheese crust in the void, where Opper-Mika guards every kaasknabbel on the starved Enderguh."),
    "barbecuether": ("De Guhbarbecuether", "The Guh Barbecuether", "barbecuether_portaal",
                     "Een hete barbecuedimensie van houtskool, roosterijzer, pindasaus en mosterd, met Spiesburchten en het Mika-grillpaleis. Je gaat erheen door een grillkoolframe.",
                     "A hot barbecue dimension of charcoal, grill iron, peanut sauce and mustard, with Spiesburchten and the Mika grill palace. You get there through a grillkool frame."),
}

# --- minigames -------------------------------------------------------------------------------------------------------------
# id -> dict(nl, en, structure, npc, bron (clothing source), munt (currency item), gids (prefix of the Guhdex highscore rows), img, lead_nl, lead_en, group)
MINIGAMES = {
    "verstopguh": dict(nl="Verstopguh", en="Hide-and-guh", structure="verstopguh_huis", npc="verstopguhtje", bron="verstop", munt="verstopguhticket",
                       gids="verstop", img="npc_verstopguhtje", group="klassiekers",
                       lead_nl="Zoek kleine guhs in het huis van Verstopguhtje, in drie moeilijkheden.", lead_en="Find little guhs hidden in Verstopguhtje's house, in three difficulties."),
    "kermis": dict(nl="De guhkermis", en="The guh fair", structure="guh_kermis", npc="kermis_guh", bron="kermis", munt="kermisbon",
                   img="kermis_coaster", group="klassiekers",
                   lead_nl="Een achtbaan vol vadsdrops en guhkurkentrekkers: elk rondje een kermisbon.", lead_en="A roller coaster full of vads drops and guh corkscrews: every ride earns a kermis ticket."),
    "beauty": dict(nl="De Vads-wedstrijd", en="The Vads contest", structure="guh_beauty_theater", npc="showguh", bron="beauty", munt="showrozet",
                   gids="beauty", img="guh_outfit_beauty", group="klassiekers",
                   lead_nl="Kleed een modelguh aan voor het thema en laat de jury van het Guh Beauty Theater oordelen.", lead_en="Dress up a model guh for the theme and let the jury of the Guh Beauty Theater judge."),
    "race": dict(nl="Guhrace", en="Guh race", structure="guh_racebaan", npc="raceguh", bron="race", munt="raceprijsje",
                 gids="race", img="structure_guh_racebaan", group="klassiekers",
                 lead_nl="Drie rondjes op een huur-renguh, door de ringen en tegen je eigen recordgeest.", lead_en="Three laps on a rented race guh, through the rings and against your own record ghost."),
    "meppen": dict(nl="Mika meppen", en="Mika whacking", structure="mika_mep_hal", npc="mepguh", bron="meppen", munt="mepmunt",
                   gids="meppen", img="structure_mika_mep_hal", group="klassiekers",
                   lead_nl="Mep de Mika's op het 4x4-bord, maar nooit de guh!", lead_en="Whack the Mikas on the 4x4 board, but never the guh!"),
    "disco": dict(nl="De Guhdisco", en="The Guh disco", structure="guh_disco", npc="djguh", bron="disco", munt="discomunt",
                  gids="disco", img="structure_guh_disco", group="klassiekers",
                  lead_nl="Dans 'Simon zegt' op de beat van vier liedjes bij de DJ-guh.", lead_en="Dance 'Simon says' to the beat of four songs with the DJ guh."),
    "golf": dict(nl="Guhgolf", en="Guh golf", structure="guh_golfbaan", npc="golfguh", bron="golf", munt="golfballetje",
                 gids="golf", img="structure_guh_golfbaan", group="klassiekers",
                 lead_nl="Negen holes minigolf met drie afslagmatjes per hole.", lead_en="Nine holes of mini golf with three tees per hole."),
    "smul": dict(nl="Het Vadsig eetfestijn", en="The Vadsig food festival", structure="vadsig_eetfestijn", npc="smulguh", bron="smul", munt="smulmunt",
                 gids="smul", img="structure_vadsig_eetfestijn", group="klassiekers",
                 lead_nl="Vang een minuut lang het vallende eten met de schaal van de Smulguh, en blijf weg van Mika-vet.", lead_en="Catch the falling food with the Smulguh's bowl for a minute, and stay away from Mika fat."),
    "vissen": dict(nl="De Guhvis-wedstrijd", en="The guh fish contest", structure="guhvis_vijver", npc="visguh", bron="vissen", munt="visbon",
                   gids="vissen", img="structure_guhvis_vijver", group="klassiekers",
                   lead_nl="Vis zo veel (en zo zwaar) mogelijk bij de Visguh; de bijzondere guhvissen mag je houden.", lead_en="Catch as many (and as heavy) fish as you can at the Visguh's pond; you keep the special guh fish."),
    "sjoelen": dict(nl="Guh-sjoelen", en="Guh shuffleboard", structure="sjoelhuisje", npc="sjoelguh", bron="sjoelen", munt="sjoelschijfje",
                    gids="sjoelen", img="structure_sjoelhuisje", group="grote_guhspelen",
                    lead_nl="Twintig schijfjes sjoelen bij Opoe Njegschuif in het Sjoelhuisje.", lead_en="Slide twenty pucks with Opoe Njegschuif in the Sjoelhuisje."),
    "doolhof": dict(nl="Het Guhdoolhof", en="The guh maze", structure="guhdoolhof", npc="doolhofguh", bron="doolhof", munt="doolhofknabbel",
                    gids="doolhof", img="structure_guhdoolhof", group="grote_guhspelen",
                    lead_nl="Een heggendoolhof dat elke keer anders is: vind de verstopte knabbels voor de Heg-Mika's ze pakken.", lead_en="A hedge maze that is different every time: find the hidden knabbels before the hedge Mikas do."),
    "katapult": dict(nl="De Knabbelkatapult", en="The knabbel catapult", structure="knabbelkatapult", npc="katapultguh", bron="katapult", munt="katapultster",
                     gids="katapult", img="structure_knabbelkatapult", group="grote_guhspelen",
                     lead_nl="Schiet pluisballen op twaalf Mika-forten met Kapitein Floepguh.", lead_en="Fire fluff balls at twelve Mika forts with Captain Floepguh."),
    "knabbelspelen": dict(nl="De Grote Zeskamp", en="The great six-event games", structure="knabbelspelen", npc="spelleiderguh", bron="knabbelspelen",
                          munt="spelenlintje", gids="spelen", img="structure_knabbelspelen", group="grote_guhspelen",
                          lead_nl="Zes spelletjes rond de circustent van De Knabbelspelen, met Juf Vahoegsakee als scheidsrechter.", lead_en="Six games around the circus tent of De Knabbelspelen, refereed by Juf Vahoegsakee."),
    "elftocht": dict(nl="De Elf-Guhjestocht", en="The eleven-guh tour", structure="elfguhjestocht", npc="schaatsmeesterguh", bron="elftocht", munt="elfstempel",
                     gids="elfguhjestocht", img="structure_elfguhjestocht", group="grote_guhspelen",
                     lead_nl="Een schaatstocht over een bevroren kanaal langs elf dorpjes in de Guhpolder: haal alle elf stempels.", lead_en="A skating tour on a frozen canal past eleven villages in the Guhpolder: collect all eleven stamps."),
    "circuit": dict(nl="Het Guh-Circuit", en="The guh circuit", structure="guh_circuit", npc="circuitguh", bron="circuit", munt="circuitbeker",
                    gids="circuit", img="structure_guh_circuit", group="grote_guhspelen",
                    lead_nl="Racen op drie banen (Regenboogbaan, Vadsbaan, Kaasbergbaan) met Coach Vahoegvroem.", lead_en="Racing on three tracks (Regenboogbaan, Vadsbaan, Kaasbergbaan) with Coach Vahoegvroem."),
    "bakkerij": dict(nl="Knabbels bakken", en="Baking knabbels", structure="knuffeldal_stadje", npc="bakkerguh", bron="bakkerij", munt="bakmunt",
                     gids="bakkerij", img="structure_bakkerij", group="knuffeldal",
                     lead_nl="Help Bakker Korstje in de Knabbelbakkerij: bak wat de klantjes willen.", lead_en="Help Baker Korstje in the Knabbelbakkerij: bake what the customers want."),
    "creche": dict(nl="De Knuffelcreche", en="The cuddle creche", structure="knuffeldal_stadje", npc="juf_knuffel", bron="creche", munt="speenmunt",
                   gids="creche", img="structure_creche", group="knuffeldal",
                   lead_nl="Breng de weggekropen babyguhtjes terug naar Juf Knuffel.", lead_en="Bring the babyguhtjes that crawled away back to Juf Knuffel."),
    "kapper": dict(nl="De kappersshow", en="The hairdresser show", structure="knuffeldal_stadje", npc="kapperguh", bron="kapper", munt="krulmunt",
                   gids="kapper", img="structure_kapper", group="knuffeldal",
                   lead_nl="Knip, krul en föhn guhs bij Kapper Krulletje in Knip & Vads.", lead_en="Cut, curl and blow-dry guhs with Kapper Krulletje in Knip & Vads."),
    "glijbanen": dict(nl="De glijbanen van het Knuffelbad", en="The Knuffelbad slides", structure="knuffelbad", npc="badmeesterguh", bron="knuffelbad",
                      munt="eendjesmunt", gids="glijbaan", img="structure_knuffelbad", group="knuffeldal",
                      lead_nl="Drie grote glijbanen (Roze Trechter, Glimtunnel en Grote Plons) in het zwembad aan de guhzee.", lead_en="Three big water slides (Roze Trechter, Glimtunnel and Grote Plons) in the pool by the guh sea."),
    "sledesprint": dict(nl="De Nomguh-sledesprint", en="The Nomguh sled sprint", structure="nomguh", npc="steele_mika", bron="sledesprint",
                        gids="sledesprint", img="shot30_baltoslee_sprint_steele_naast_je", group="verhalen",
                        lead_nl="Een sledesprint door de sneeuw tegen Steele-Mika, na het verhaal van Nomguh.", lead_en="A sled sprint through the snow against Steele-Mika, after the Nomguh story."),
    "surfen": dict(nl="Surfen", en="Surfing", structure="guhwaii_surfstrand", npc="lilo_guh", bron="guhwaii_spellen", munt="schelpjesmunt",
                   gids="surfen", img="shot30_guhwaiispellen_surfen", group="verhalen",
                   lead_nl="Surf met Lilo-guh over de golven van het surfstrand van Guhwai'i.", lead_en="Surf the waves of the Guhwai'i surf beach with Lilo-guh."),
    "hula": dict(nl="Hula", en="Hula", structure="guhwaii_surfstrand", npc="lilo_guh", bron="guhwaii_spellen", munt="schelpjesmunt",
                 gids="hula", img="shot30_guhwaiispellen_hula", group="verhalen",
                 lead_nl="Dans de hula op het strand van Guhwai'i: kies een liedje en volg de pasjes.", lead_en="Dance the hula on the Guhwai'i beach: pick a song and follow the steps."),
}
MINIGAME_GROUPS = {"klassiekers": ("Klassiekers", "Classics"), "grote_guhspelen": ("De Grote Guhspelen", "The Grote Guhspelen"),
                   "knuffeldal": ("Knuffeldal", "Knuffeldal"), "verhalen": ("Guhverhalen", "Guh stories")}

# --- stories and questlines --------------------------------------------------------------------------------------------------
# id -> dict(nl, en, img, lead_nl, lead_en, ftb=[(chapter, section id or None = whole chapter)], structure, npcs, reward (clothing bron / variant))
STORIES = {
    "moeder-vadsig": dict(nl="Moeder Vadsig en Guhbert", en="Mother Vadsig and Guhbert", img="npc_moeder_vadsig",
                          ftb=[("guhs_maag", None)], structure="vadsig_heiligdom", npcs=["moeder_vadsig", "tandarts", "maagenzym"],
                          related=["dimensies/guhmaag", "bouwwerken/mika_kamp", "bouwwerken/guh_picnic"],
                          lead_nl="Help Moeder Vadsig haar kleine Guhbert terug te vinden: bevrijd hem uit het Mika-kamp, vind de verloren guhtaart en vier feest. Als dank krijg je je eigen guhmaag.",
                          lead_en="Help Mother Vadsig find her little Guhbert: free him from the Mika camp, find the lost guh cake and have a party. As a thank-you you get your own guh stomach."),
    "kapotte-slee": dict(nl="De kapotte slee", en="The broken sled", img="npc_slee_guh", structure="sleehut", npcs=["slee_guh"],
                         related=["systemen/guhslee"],
                         lead_nl="De slee van de Slee-guh op de Guhpieken is kapot. Vind een sleeglijder, een guhbelletje en een roze lint, en ze leert je rails bouwen.",
                         lead_en="The Sled Guh's sled on the Guh Peaks is broken. Find a sled runner, a guh bell and a pink ribbon, and she teaches you to build rails."),
    "guheinde": dict(nl="Het Grote Knabbelroof", en="The Great Knabbel Heist", img="opper_mika", ftb=[("guhs_guheinde", None)],
                     structure="knabbelkelder", npcs=["koning"], related=["dimensies/guheinde", "wezens/opper_mika", "guhs/vahoege_ender"],
                     lead_nl="Opper-Mika heeft alle kaasknabbels gestolen. Maak twaalf Ogen van Vadsig, vind de Knabbelkelder, open het portaal en versla hem in het Guheinde.",
                     lead_en="Opper-Mika has stolen every kaasknabbel. Make twelve Eyes of Vadsig, find the Knabbelkelder, open the portal and beat him in the Guheinde."),
    "grillguh": dict(nl="De Aanmaakblokjes van de Grillguh", en="The Grillguh's fire starters", img="npc_grillguh",
                     ftb=[("guhs_barbecuether", None)], structure="barbecueput", npcs=["grillguh"], related=["dimensies/barbecuether"],
                     lead_nl="De Mika's hebben de Aanmaakblokjes van de Grillguh gejat. Maak zijn barbecue weer heel en hij leert je zijn geheime grillrecept.",
                     lead_en="The Mikas stole the Grillguh's fire starters. Fix his barbecue and he teaches you his secret grill recipe."),
    "knusfeest": dict(nl="Het Grote Knusfeest", en="The Great Cosy Party", img="npc_burgemeesterguh", ftb=[("guhs_knuffeldal", "knusfeest")],
                      structure="knuffeldal_stadje", npcs=["burgemeesterguh"], related=["biomen/knuffeldal"],
                      lead_nl="Burgemeester Vadsema organiseert het Grote Knusfeest. Doe de zes feesttaakjes, houd de Kruimel-Mika's weg van het buffet en vier feest.",
                      lead_en="Mayor Vadsema is throwing the Great Cosy Party. Do the six party chores, keep the Kruimel-Mikas away from the buffet and celebrate."),
    "beroepen": dict(nl="Beroepen", en="Jobs", img="beroepen_npcs", ftb=[("guhs_knuffeldal", "beroepen")], structure="knuffeldal_stadje",
                     npcs=["brandweerguh", "politieguh", "apothekerguh", "bouwvakkerguh"],
                     lead_nl="Vier beroepen, elk één keer: help de brandweer, de politie, de apotheek en Bob de Guhbouwer, en verdien hun werkkleding.",
                     lead_en="Four jobs, one time each: help the fire brigade, the police, the pharmacy and Bob the Guh Builder, and earn their work clothes."),
    "timmerguh": dict(nl="Samen een huisje bouwen", en="Building a house together", img="npc_timmerguh", ftb=[("guhs_verhalen", "timmerguh")],
                      structure="knuffeldal_stadje", npcs=["timmerguh"], related=["systemen/guhhuisje"],
                      lead_nl="Aan de rand van elk Knuffeldal-stadje bouwt de Timmerguh een guhhuisje. Help hem en leer zelf guhhuisjes bouwen.",
                      lead_en="At the edge of every Knuffeldal town the Timmerguh is building a guh house. Help him and learn to build guh houses yourself."),
    "nomguh": dict(nl="Baltoguh en Nomguh", en="Baltoguh and Nomguh", img="guh_variant_baltoguh", ftb=[("guhs_verhalen", "balto")],
                   structure="nomguh", npcs=["boris", "steele_mika", "muk", "luk", "rosy", "witte_wolfguh"], related=["guhs/baltoguh", "biomen/sneeuwguhtoendra"],
                   lead_nl="In het besneeuwde guhstadje Nomguh is Rosy ziek. Alleen Baltoguh, half guh en half wolf, kan het medicijn door de storm halen.",
                   lead_en="In the snowy guh town of Nomguh, Rosy is ill. Only Baltoguh, half guh and half wolf, can bring the medicine through the storm."),
    "sneeuwstorm": dict(nl="Door de sneeuwstorm", en="Through the snowstorm", img="shot30_gui_baltoslee_tocht_storm", ftb=[("guhs_verhalen", "balto_slee")],
                        structure="nomguh", npcs=["steele_mika"], related=["verhalen/nomguh", "minigames/sledesprint"],
                        lead_nl="De medicijnrit met de hondenslee van Nomguh: door de sneeuwstorm naar de berghut en terug.",
                        lead_en="The medicine ride with the Nomguh dog sled: through the snowstorm to the mountain hut and back."),
    "kloon-eiland": dict(nl="Het kloon-eiland", en="The clone island", img="npc_knabbelkloon", ftb=[("guhs_verhalen", "mewtwo")],
                         structure="kloon_eiland", npcs=["knabbelkloon"], related=["guhs/mewtwo", "diertjes/mew", "diertjes/shuckle"],
                         lead_nl="Professor Knabbelkloon wilde een guh klonen die dubbel zoveel kaasknabbels kon eten. Het werd de Guhtwo.",
                         lead_en="Professor Knabbelkloon wanted to clone a guh that could eat twice as many kaasknabbels. It became the Guhtwo."),
    "hemelkapelletje": dict(nl="Het Hemelkapelletje en het Knuffelhart", en="The sky chapel and the cuddle heart", img="npc_wolkenhoeder",
                            ftb=[("guhs_verhalen", "hemel")], structure="hemelkapelletje", npcs=["wolkenhoeder"],
                            lead_nl="Hoog in de wolken past de wolkenhoeder op het Knuffelhart. Laat het weer kloppen, en een getemde guh die sterft komt als wolkje terug.",
                            lead_en="High in the clouds the cloud keeper looks after the cuddle heart. Make it beat again, and a tamed guh that dies comes back as a little cloud."),
    "ohana": dict(nl="Ohana op Guhwai'i", en="Ohana on Guhwai'i", img="guh_variant_stitch626", ftb=[("guhs_verhalen", "guhwaii")],
                  structure="guhwaii_ohana", npcs=["lilo_guh", "nani_guh"], related=["guhs/stitch626", "biomen/guhwaii", "bouwwerken/guhwaii_capsule"],
                  lead_nl="Op Guhwai'i is een capsule neergestort, met Experiment 626 erin. Lilo-guh wil hem als huisdier. Ohana betekent familie!",
                  lead_en="A capsule crashed on Guhwai'i, with Experiment 626 inside. Lilo-guh wants him as a pet. Ohana means family!"),
}

# --- mechanics ---------------------------------------------------------------------------------------------------------------
# id -> (NL title, EN title, picture, NL lead, EN lead, related)
SYSTEMS = {
    "temmen": ("Temmen, rijden en oppakken", "Taming, riding and picking up", "guh_saddle",
               "Een wilde guh tem je met kaasknabbels. Een tamme guh kun je berijden, oppakken, aankleden en lanceren.",
               "You tame a wild guh with kaasknabbels. A tamed guh can be ridden, picked up, dressed up and launched.", ["systemen/karakters", "systemen/hartjes"]),
    "karakters": ("Karakters", "Personalities", "guh_sitting",
                  "Elke guh heeft een karakter: speels, lui, vadsig, verlegen, dapper, kletskous, knuffelig of nieuwsgierig.",
                  "Every guh has a personality: playful, lazy, vadsig, shy, brave, chatty, cuddly or curious.", ["systemen/temmen"]),
    "hartjes": ("Hartjes en de zielsguh", "Hearts and the soul guh", "band_niveaus",
                "De hartjesmeter: hoe meer je met je guh doet, hoe meer hartjes. Hartjes gaan nooit omlaag, en bij het hoogste niveau wordt je guh je zielsguh.",
                "The heart meter: the more you do with your guh, the more hearts. Hearts never go down, and at the top level your guh becomes your soul guh.",
                ["systemen/favorietjes", "systemen/samen"]),
    "favorietjes": ("Favorietjes", "Favourites", "shot210_favorietjes_explosie",
                    "Elke guh heeft acht geheime favorietjes. Raad ze (warm of koud?) en je guh wordt blij.",
                    "Every guh has eight secret favourites. Guess them (warm or cold?) and your guh gets happy.", ["systemen/hartjes"]),
    "guhhuisje": ("Het Guhhuisje", "The guh house", "guhhuisjes",
                  "Een huisje in de vorm van een guhhoofd, in drie maten: daar wonen je guhs, slapen ze 's nachts en doen ze overdag klusjes.",
                  "A little house shaped like a guh head, in three sizes: your guhs live there, sleep there at night and do chores in the day.",
                  ["systemen/klusjes", "verhalen/timmerguh"]),
    "klusjes": ("Klusjes", "Chores", "shot210_klusjes_erf_bezig",
                "Guhs die in een guhhuisje wonen doen overdag tien soorten klusjes rond hun huisje.",
                "Guhs that live in a guh house do ten kinds of chores around it during the day.", ["systemen/guhhuisje"]),
    "speelgoed": ("Speelgoed", "Toys", "shot210_speelgoed_spelen2",
                  "Een guhspeeltuin: knabbelbal, glijbaantje, pluizige tunnel, wip en schommel.",
                  "A guh playground: knabbel ball, little slide, fluffy tunnel, seesaw and swing.", ["systemen/samen"]),
    "samen": ("Samen", "Together", "shot210_samen_juichen",
              "Je guhs juichen je toe bij minigames, rijden achterop mee en sluiten vriendschap met elkaar.",
              "Your guhs cheer for you in minigames, ride along on the back and make friends with each other.", ["systemen/hartjes"]),
    "guhkamer": ("De Guhkamer", "The guh room", "shot210_guhkamer_binnen",
                 "Een logeerkamer in je guhmaag, waar je guhs op bezoek komen.", "A guest room in your guh stomach, where your guhs come to stay.",
                 ["dimensies/guhmaag"]),
    "guhmenu": ("Het guhmenu", "The guh menu", "shot30_gui_guhmenu_dagboekje",
                "Houd rechtsklik ingedrukt op je guh: het menu met aaien, knuffelen, emotes, kleding, het dagboekje en de Guhkamer.",
                "Hold right-click on your guh: the menu with petting, hugging, emotes, clothes, the diary and the guh room.", ["systemen/emotes", "systemen/kleding"]),
    "kleding": ("Kleding en de kledingkast", "Clothes and the wardrobe", "shot29_kast_hoofd",
                "Kleed je guh aan: zeven vakjes, meer dan honderd kledingstukken en de kledingkast. Een kledingstuk eet je één keer op en dan is het voor altijd van jou.",
                "Dress up your guh: seven slots, more than a hundred pieces and the wardrobe. Eat a piece once and it is yours forever.", ["kleding/index"]),
    "guhdex": ("De Guhdex", "The Guhdex", "icon_guhdex",
               "Het boek van alle guhs, personages en diertjes die je tegenkwam, met tabs voor Knus, Minigames, Kleding en Mijn guhs.",
               "The book of every guh, character and critter you met, with tabs for Knus, Minigames, Clothes and My guhs.", ["guhs/index", "systemen/superkompas"]),
    "superkompas": ("Het superkompas", "The super compass", "icon_guhmensie_superkompas_00",
                    "Het Guhmensie-superkompas wijst de weg naar (bijna) elk bouwwerk, per tab: Avontuur, Quests, Minigames, Wonderen, Wonen, Einde, Ondergrond, Barbecue, Knus en Verhalen.",
                    "The Guhmension super compass points the way to (almost) every structure, by tab: Adventure, Quests, Minigames, Wonders, Homes, End, Underground, Barbecue, Cosy and Stories.",
                    ["bouwwerken/index"]),
    "ftb-quests": ("FTB-quests", "FTB quests", "icon_timmerguh_bouwboekje",
                   "Met FTB Quests in je pack krijg je vanzelf een Guhs-hoofdstukgroep in het questboek. Niks zit op slot.",
                   "With FTB Quests in your pack you automatically get a Guhs chapter group in the quest book. Nothing is locked.", ["verhalen/index"]),
    "emotes": ("Emotes", "Emotes", "shot210_gui_samen_emotes", "Je guh kan zwaaien, dansen, knuffelen, gapen en nog veel meer.",
               "Your guh can wave, dance, hug, yawn and much more.", ["systemen/guhmenu"]),
    "evenementen": ("Evenementen", "Events", "guh_outfit_evenementen",
                    "Af en toe gebeurt er iets bijzonders in de Guhmensie: een kaasregen, de Vadsparade, een sterrenregen of het Knusfeest.",
                    "Now and then something special happens in the Guhmension: a cheese rain, the Vads parade, a star shower or the cosy party.", []),
    "guhslee": ("De guhslee en sleerails", "The guh sled and sled rails", "guh_slee",
                "Bouw een sleebaan met sleerails en rijd met je guhs in de guhslee, met bochten, drops, kurkentrekkers en schansen.",
                "Build a sled track with sled rails and ride the guh sled with your guhs, with curves, drops, corkscrews and jumps.", ["verhalen/kapotte-slee"]),
    "verhaalguhs": ("Verhaalguhs", "Story guhs", "verhaalguhs_30",
                    "Baltoguh, Guhtwo en 626-guh: elk verhaal eindigt met een nieuwe vriend die je (per speler) één keer mag temmen.",
                    "Baltoguh, Guhtwo and 626 guh: every story ends with a new friend that you (per player) can tame once.",
                    ["guhs/baltoguh", "guhs/mewtwo", "guhs/stitch626"]),
    "seizoenen": ("Seizoenen en het dagritme", "Seasons and the day rhythm", "seizoensbloembakken",
                  "Het Knuffeldal kent vier seizoenen en een dagritme: de guhs doen elk uur iets anders.",
                  "The Knuffeldal has four seasons and a day rhythm: the guhs do something different every hour.", ["biomen/knuffeldal"]),
    "moeilijkheid": ("Makkelijk, medium of lastig", "Easy, medium or hard", "shot29_scherm_meppen",
                     "Bij bijna elke minigame kies je hoe moeilijk je het wilt: makkelijk, medium of lastig.",
                     "In almost every minigame you choose how hard you want it: easy, medium or hard.", ["minigames/index"]),
    "brouwen": ("De Guhbrouwketel", "The guh brewing kettle", "guhbrouwketel_vahoegheid_3",
                "Brouw guhdrankjes in de Guhbrouwketel.", "Brew guh potions in the guh brewing kettle.", ["blokken/guhbrouwketel"]),
    "vahoege-vads": ("Vahoege vads", "Vahoege vads", "compressed_super_vahoege_vads",
                     "Het sterkste metaal van de Guhmensie: gereedschap en harnas die nooit kapotgaan.",
                     "The strongest metal of the Guhmension: tools and armour that never break.", []),
    "commandos": ("Commando's", "Commands", "icon_guhdex",
                  "Handige commando's voor creative en voor operators.", "Handy commands for creative mode and for operators.", []),
    "vooruitgangen": ("Vooruitgangen", "Advancements", "icon_guhdex",
                      "Alle vooruitgangen van Guhs, per tabblad.", "All the advancements of Guhs, by tab.", ["systemen/ftb-quests"]),
    "guhboeken": ("De guhboeken", "The guh books", "structure_guhbibliotheek",
                  "De boeken van de guhbibliotheek: lees ze op de lessenaars.", "The books of the guh library: read them on the lecterns.",
                  ["bouwwerken/guhbibliotheek"]),
    "knuffels": ("Guhknuffels", "Guh plushies", "knuffels",
                 "Verzamel de knuffels van alle guhs.", "Collect the plushies of all the guhs.", []),
    "effecten": ("Effecten", "Effects", "icon_stille_knabbel",
                 "De effecten die Guhs toevoegt.", "The effects that Guhs adds.", []),
}

# --- links the data doesn't spell out -------------------------------------------------------------------------------------------
# variant -> the page where you find it
VARIANT_HOME = {
    "koning": "bouwwerken/guh_kasteel", "wolk": "bouwwerken/zwevende_eilanden", "zeemeerguh": "bouwwerken/onderwater",
    "mager": "bouwwerken/knabbelkelder", "vahoege_ender": "dimensies/guheinde", "kaasmoerasguh": "biomen/kaasmoeras",
    "asguh": "biomen/asdal", "pluisguh": "biomen/knuffeldal", "pinguh": "biomen/guhpolder", "golden": "bouwwerken/guhramid",
    "ender": "biomen/guh_peaks", "snow": "biomen/guh_peaks", "brococolief": "bouwwerken/guh_village",
    "baltoguh": "verhalen/nomguh", "mewtwo": "verhalen/kloon-eiland", "stitch626": "verhalen/ohana",
}
# NPC kind (or villager profession) -> where it lives
NPC_HOME = {
    "moeder_vadsig": "bouwwerken/vadsig_heiligdom", "tandarts": "dimensies/guhmaag", "maagenzym": "dimensies/guhmaag",
    "slee_guh": "bouwwerken/sleehut", "kermis_guh": "bouwwerken/guh_kermis", "verstopguhtje": "bouwwerken/verstopguh_huis",
    "tipguh": "bouwwerken/verstopguh_huis", "poortwachter": "bouwwerken/guh_kasteel", "showguh": "bouwwerken/guh_beauty_theater",
    "raceguh": "bouwwerken/guh_racebaan", "mepguh": "bouwwerken/mika_mep_hal", "djguh": "bouwwerken/guh_disco",
    "golfguh": "bouwwerken/guh_golfbaan", "smulguh": "bouwwerken/vadsig_eetfestijn", "visguh": "bouwwerken/guhvis_vijver",
    "mijnguh": "bouwwerken/kaasmijn", "bibliothecaris": "bouwwerken/guhbibliotheek", "zeemeerguh": "bouwwerken/onderwater",
    "boswachterguh": "bouwwerken/boomhutdorp", "knabbelplukker": "bouwwerken/boomhutdorp", "grillguh": "bouwwerken/barbecueput",
    "burgemeesterguh": "bouwwerken/knuffeldal_stadje", "bakkerguh": "bouwwerken/knuffeldal_stadje", "juf_knuffel": "bouwwerken/knuffeldal_stadje",
    "theeguh": "bouwwerken/knuffeldal_stadje", "kapperguh": "bouwwerken/knuffeldal_stadje", "boerinneguh": "bouwwerken/guhboerderij",
    "sterrenkijkerguh": "bouwwerken/guh_sterrenwacht", "ballonguh": "bouwwerken/ballonfestival", "opa_guh": "bouwwerken/kampeerplekje",
    "badmeesterguh": "bouwwerken/knuffelbad", "cocotje": "bouwwerken/knuffeldal_stadje", "sjoelguh": "bouwwerken/sjoelhuisje",
    "doolhofguh": "bouwwerken/guhdoolhof", "katapultguh": "bouwwerken/knabbelkatapult", "spelleiderguh": "bouwwerken/knabbelspelen",
    "schaatsmeesterguh": "bouwwerken/elfguhjestocht", "stempelguh": "bouwwerken/elfguhjestocht", "circuitguh": "bouwwerken/guh_circuit",
    "brandweerguh": "bouwwerken/knuffeldal_stadje", "politieguh": "bouwwerken/knuffeldal_stadje", "apothekerguh": "bouwwerken/knuffeldal_stadje",
    "bouwvakkerguh": "bouwwerken/guh_village", "timmerguh": "bouwwerken/knuffeldal_stadje", "boris": "bouwwerken/nomguh",
    "steele_mika": "bouwwerken/nomguh", "muk": "bouwwerken/nomguh", "luk": "bouwwerken/nomguh", "rosy": "bouwwerken/nomguh",
    "witte_wolfguh": "verhalen/sneeuwstorm", "knabbelkloon": "bouwwerken/kloon_eiland", "wolkenhoeder": "bouwwerken/hemelkapelletje",
    "lilo_guh": "bouwwerken/guhwaii_ohana", "nani_guh": "bouwwerken/guhwaii_ohana", "tikiguh": "bouwwerken/guhwaii_surfstrand",
    "reisguh": "dimensies/guhmension", "quest_guh": "bouwwerken/guh_picnic", "ijscoguh": "dimensies/guhmension",
    "creche_babyguh": "minigames/creche", "tamboerguh": "systemen/evenementen",
    "vads_temmer": "bouwwerken/guh_village", "guh_kleermaker": "bouwwerken/guh_village", "vadssmid": "bouwwerken/guh_village",
    "hamsterbouwer": "bouwwerken/guh_village", "mika_jager": "bouwwerken/guh_village", "knabbelboer": "bouwwerken/guh_village",
}
# NPC kind -> the story it plays in
NPC_STORY = {"moeder_vadsig": "moeder-vadsig", "slee_guh": "kapotte-slee", "grillguh": "grillguh", "burgemeesterguh": "knusfeest",
             "brandweerguh": "beroepen", "politieguh": "beroepen", "apothekerguh": "beroepen", "bouwvakkerguh": "beroepen",
             "timmerguh": "timmerguh", "boris": "nomguh", "steele_mika": "nomguh", "muk": "nomguh", "luk": "nomguh", "rosy": "nomguh",
             "witte_wolfguh": "sneeuwstorm", "knabbelkloon": "kloon-eiland", "wolkenhoeder": "hemelkapelletje", "lilo_guh": "ohana",
             "nani_guh": "ohana", "tandarts": "moeder-vadsig", "maagenzym": "moeder-vadsig"}

# entity ids: the critters, the mobs and the things that get no page of their own (the rest become "wezens" automatically)
CRITTERS = ["pluisvinkje", "kaasmeesje", "guh_uiltje", "zeemeeuwtje", "guhxolotl", "guh_eendje", "knabbelvlindertje", "glimguhtje",
            "lieveheersbeestje", "pluisegeltje", "guh_konijntje", "pluiseekhoorntje", "shuckle", "mew", "kikkerguh", "kaasmot",
            "guhschaapje", "knabbelkippetje", "guhkoe", "pieppiepmuisje", "poepschilly", "schilly", "guh_vis", "guh_bee", "guh_slime"]
BOSSES = {"big_mika", "mika_baas", "opper_mika", "aangebrande_mika", "boze_oppernabbel", "vadswaker"}
NPC_ENTITIES = {"quest_guh": "npc_quest_guh", "ijscoguh": "ijscoguh", "creche_babyguh": "creche_babyguh", "tamboerguh": None, "parade_guh": None}
NO_PAGE = {"guh", "guh_npc", "baltoguh", "mewtwo", "stitch626", "witte_wolfguh", "badeendje", "bakkerij_klant", "baltoslee_sledehondje",
           "baltoslee_slee", "beauty_model", "beroepen_boomguhtje", "beroepen_snotje", "brandend_kooltje", "gloeiend_kooltje",
           "circuit_rolknabbel", "guh_golfbal", "guh_luchtballon", "guh_slee", "guhwaiispellen_surfplank", "kapper_klant",
           "katapult_brokje", "knabbelbal", "knabbelspelen_ding", "mika_vetbal", "oog_van_vadsig", "pluisbal", "race_ghost", "race_guh",
           "sjoelschijf", "smul_hapje", "sneeuwslee", "speelgoed_zitje", "vadsverdrijvend_drankje", "vallende_knabbel",
           "vallende_ster", "zwembandje", "parade_guh"}
# entity -> where it is (when the spawn data has nothing)
ENTITY_HOME = {
    "mika": "biomen/mikas_biome", "big_mika": "bouwwerken/challenging_guh_caves", "mika_baas": "bouwwerken/mika_kamp",
    "opper_mika": "dimensies/guheinde", "hongerige_enderguh": "dimensies/guheinde", "knabbelkristal": "dimensies/guheinde",
    "mika_larfje": "bouwwerken/knabbelkelder", "vadswaker": "bouwwerken/stille_voorraadkelder", "moerasheks_mika": "bouwwerken/moerasheks_hut",
    "aangebrande_mika": "dimensies/barbecuether", "kruimel_mika": "verhalen/knusfeest", "boze_kaasknabbel": "bouwwerken/kaasknabbel_nest",
    "boze_oppernabbel": "bouwwerken/kaasknabbel_nest", "doolhof_mika": "minigames/doolhof", "circuit_mikapikker": "minigames/circuit",
    "knabbeldief_mika": "verhalen/beroepen", "mew": "bouwwerken/kloon_eiland", "pieppiepmuisje": "bouwwerken/hamster_house",
    "guhschaapje": "bouwwerken/guhboerderij", "knabbelkippetje": "bouwwerken/guhboerderij", "guhkoe": "bouwwerken/guhboerderij",
    "kikkerguh": "biomen/kaasmoeras", "kaasmot": "biomen/kaasmoeras", "rookguh": "dimensies/barbecuether", "vonk_mika": "bouwwerken/spiesburcht",
    "knekel_mika": "dimensies/barbecuether", "nether_mika": "dimensies/barbecuether",
}
# structure ids without a lang name
STRUCTURE_NAMES = {"block_guh": ("Blokguh", "Block guh"), "giant_cake": ("Reuzentaart", "Giant cake"),
                   "giant_kaasknabbel": ("Reuzenkaasknabbel", "Giant kaasknabbel"), "guh_fossil": ("Guhfossiel", "Guh fossil"),
                   "kaasknabbel_arch": ("Kaasknabbelboog", "Kaasknabbel arch"), "mini_picnic": ("Minipicknick", "Mini picnic"),
                   "quartz_statue": ("Kwartsbeeldje", "Quartz statue"), "mika_vesting": ("Mika-vesting", "Mika fortress")}
# pictures that belong to a structure page but aren't called structure_<id>
STRUCTURE_PICS = {
    "guh_caves": ["structure_central_room", "structure_nest_room", "structure_pantry_room"],
    "challenging_guh_caves": ["structure_dungeon_hall", "structure_parkour_room", "structure_spawner_room", "structure_mika_den"],
    "barbecueput": ["structure_barbecueput_groot", "structure_barbecueput_klein"],
    "mika_vesting": ["structure_mika_vesting_schip"],
    "guh_village": ["structure_layout_a", "shot29_guhdorp_layout_c_zuid"],
    "knuffeldal_stadje": ["structure_knuffeldal_plein", "structure_theehuis", "shot29_gebouw_knuffeldal_stadje_3_close"],
    "guh_kasteel": ["guh_kasteel_poort", "guh_kasteel_hoofd", "guh_kasteel_troonzaal"],
    "kaasmijn": ["kaasmijn_gangen"], "verstopguh_huis": ["verstopguh_huis_beneden", "verstopguh_huis_glas"],
    "nomguh": ["shot30_balto_nomguh_overzicht", "shot30_balto_nomguh_plein", "shot30_balto_nomguh_boot"],
    "kloon_eiland": ["shot30_mewtwo_eiland_overzicht", "shot30_mewtwo_arena", "shot30_mewtwo_steiger"],
    "hemelkapelletje": ["shot30_hemel_kapelletje", "shot30_hemel_kapel_binnen"],
    "guhwaii_ohana": ["shot30_guhwaii_ohana_keuken", "shot30_guhwaii_ohana_lilo_kamer"],
    "guhwaii_capsule": ["shot30_guhwaii_capsule_binnen", "shot30_guhwaii_capsule_poster"],
    "elfguhjestocht": ["shot210_elftocht_bovenaf", "shot210_elftocht_overzicht_zuid", "shot210_elftocht_startboog"],
    "guh_kermis": ["kermis_coaster"], "kaasknabbel_nest": ["kaasknabbel_nest_arena", "shot_piep_nest_zuid"],
    "guhdoolhof": ["shot210_doolhof_bovenaf"], "guh_golfbaan": ["shot210_golf_bovenaf"],
}
# biome -> its pictures
BIOME_PICS = {"diepe_guhzee": ["diepe_guhzee"], "gatenkaasgrotten": ["gatenkaas"], "kaasmoeras": ["borrelende_kaassaus"],
              "vadswoud": ["vadshout_gezichtjes"], "guhpolder": ["shot29_biome_guhpolder"], "sneeuwguhtoendra": ["shot30_biome_guhmension_sneeuwguhtoendra"],
              "guhwaii": ["shot30_biome_guhmension_guhwaii"], "guh_kristalmijn": ["guh_kristal_cluster"], "knuffeldal": ["structure_knuffeldal_stadje"],
              "guh_fields": ["roze_gras"], "guh_meadows": ["roze_guhbloem"], "pink_puffs": ["pink_kussen"], "kaas_flats": ["block_of_kaasknabbels"],
              "knabbel_crumbs": ["kaasknabbel_dirt"], "guh_peaks": ["guh_variant_ender"], "vads_cliffs": ["vadsaambeeld"],
              "mikas_biome": ["mika"], "guh_sea": ["guh_vis"], "guhmaag": ["maagwand"], "guheinde": ["structure_guheinde_knabbelberg"],
              "houtskoolvlakte": ["houtskoolsteen"], "asdal": ["as_blok"], "satebos": ["sate_stam"], "worstenwoud": ["worst_stam"],
              "rookdelta": ["rookgat"]}
# outfit render -> clothing source (bron)
OUTFIT_PICS = {
    "guh_outfit_onesie": "brococolief", "guh_outfit_sweater": "kleermaker", "guh_outfit_rain": "kleermaker", "guh_outfit_party": "loot_picknick",
    "guh_outfit_chef": "bakkerij", "guh_outfit_work_fire": "beroep_brandweer", "guh_outfit_work_police": "beroep_politie",
    "guh_outfit_work_doctor": "beroep_apotheek", "guh_outfit_work_builder": "beroep_bouw", "guh_outfit_work_farmer": "boerderij",
    "guh_outfit_holiday_christmas": "loot_picknick", "guh_outfit_holiday_sint": "loot_hamsterhuis", "guh_outfit_holiday_piet": "loot_hamsterhuis",
    "guh_outfit_holiday_halloween": "loot_mikahuis", "guh_outfit_holiday_witch": "loot_mikahuis", "guh_outfit_holiday_kingsday": "loot_picknick",
    "guh_outfit_fantasy_wizard": "loot_guhramid", "guh_outfit_fantasy_knight": "loot_grotten", "guh_outfit_fantasy_royal": "loot_guhramid",
    "guh_outfit_fantasy_pirate": "loot_grotten", "guh_outfit_kermis": "kermis", "guh_outfit_detective": "verstop", "guh_koning_pakje": "loot_kasteel",
    "guh_outfit_beauty": "beauty", "guh_outfit_race": "race", "guh_outfit_meppen": "meppen", "guh_outfit_disco": "disco", "guh_outfit_golf": "golf",
    "guh_outfit_smul": "smul", "guh_outfit_vissen": "vissen", "guh_outfit_eilanden": "loot_eilanden", "guh_outfit_kaasmijn": "kaasmijn",
    "guh_outfit_bibliotheek": "bibliotheek", "guh_outfit_onderwater": "onderwater", "guh_outfit_evenementen": "vadsparade",
    "guh_outfit_boswachter": "vadswoud", "guh_outfit_pluk": "vadswoud", "guh_outfit_vadswoud": "vadswoud", "guh_outfit_grill": "barbecuether",
    "guh_outfit_barbecuether": "barbecuether", "guh_outfit_knuffeldal": "knuffeldal", "guh_outfit_bakkerij": "bakkerij", "guh_outfit_creche": "creche",
    "guh_outfit_theehuis": "theehuis", "guh_outfit_kapper": "kapper", "guh_outfit_boerderij": "boerderij", "guh_outfit_tuintjes": "tuintjes",
    "guh_outfit_sterrenwacht": "sterrenwacht", "guh_outfit_ballon": "ballon", "guh_outfit_kamperen": "kamperen", "guh_outfit_knuffelbad": "knuffelbad",
    "guh_outfit_wereldleven": "wereldleven", "guh_outfit_sjoelen": "sjoelen", "guh_outfit_doolhof": "doolhof", "guh_outfit_katapult": "katapult",
    "guh_outfit_knabbelspelen": "knabbelspelen", "guh_outfit_elftocht": "elftocht", "guh_outfit_circuit": "circuit", "guh_outfit_samen": "band",
    "guh_outfit_timmerguh": "timmerguh", "guh_outfit_timmerguh_back": "timmerguh", "guh_outfit_balto": "nomguh", "guh_outfit_balto_back": "nomguh",
    "guh_outfit_mewtwo": "mewtwo", "guh_outfit_mewtwo_back": "mewtwo", "guh_outfit_hemel": "hemel", "guh_outfit_hemel_back": "hemel",
    "guh_outfit_guhwaii": "guhwaii", "guh_outfit_guhwaii_back": "guhwaii",
}
# clothing source -> the page it links to (a minigame, story, structure...)
BRON_PAGE = {
    "kermis": "minigames/kermis", "verstop": "minigames/verstopguh", "beauty": "minigames/beauty", "race": "minigames/race",
    "meppen": "minigames/meppen", "disco": "minigames/disco", "golf": "minigames/golf", "smul": "minigames/smul", "vissen": "minigames/vissen",
    "sjoelen": "minigames/sjoelen", "doolhof": "minigames/doolhof", "katapult": "minigames/katapult", "knabbelspelen": "minigames/knabbelspelen",
    "elftocht": "minigames/elftocht", "circuit": "minigames/circuit", "sledesprint": "minigames/sledesprint", "guhwaii_spellen": "minigames/surfen",
    "bakkerij": "minigames/bakkerij", "creche": "minigames/creche", "kapper": "minigames/kapper", "knuffelbad": "minigames/glijbanen",
    "kleermaker": "npcs/guh_kleermaker", "loot_picknick": "bouwwerken/guh_picnic", "loot_hamsterhuis": "bouwwerken/hamster_house",
    "loot_guhramid": "bouwwerken/guhramid", "loot_mikahuis": "bouwwerken/evil_mika_home", "loot_grotten": "bouwwerken/guh_caves",
    "loot_kasteel": "bouwwerken/guh_kasteel", "loot_eilanden": "bouwwerken/zwevende_eilanden", "guhdex": "systemen/guhdex",
    "brococolief": "guhs/brococolief", "vadsparade": "systemen/evenementen", "kaasmijn": "bouwwerken/kaasmijn",
    "bibliotheek": "bouwwerken/guhbibliotheek", "onderwater": "bouwwerken/onderwater", "vadswoud": "bouwwerken/boomhutdorp",
    "barbecuether": "verhalen/grillguh", "knuffeldal": "verhalen/knusfeest", "theehuis": "bouwwerken/knuffeldal_stadje",
    "boerderij": "bouwwerken/guhboerderij", "tuintjes": "bouwwerken/guhboerderij", "sterrenwacht": "bouwwerken/guh_sterrenwacht",
    "ballon": "bouwwerken/ballonfestival", "kamperen": "bouwwerken/kampeerplekje", "wereldleven": "npcs/ijscoguh",
    "beroep_brandweer": "verhalen/beroepen", "beroep_politie": "verhalen/beroepen", "beroep_apotheek": "verhalen/beroepen",
    "beroep_bouw": "verhalen/beroepen", "band": "systemen/hartjes", "timmerguh": "verhalen/timmerguh", "nomguh": "verhalen/nomguh",
    "mewtwo": "verhalen/kloon-eiland", "hemel": "verhalen/hemelkapelletje", "guhwaii": "verhalen/ohana", "crafting": "systemen/kleding",
    "grijpmachine": "blokken/grijpmachine",
}
# chest loot table -> structure
LOOT_STRUCTURE = {"barbecueput_groot": "barbecueput", "barbecueput_klein": "barbecueput", "boomhutdorp_uitkijk": "boomhutdorp",
                  "challenging_guh_caves_treasure": "challenging_guh_caves", "grillpaleis_schat": "mika_grillpaleis",
                  "grillpaleis_voorraad": "mika_grillpaleis", "guh_kasteel_schat": "guh_kasteel", "guhbibliotheek_archief": "guhbibliotheek",
                  "guhramid_secret": "guhramid", "kaasknabbel_nest_schat": "kaasknabbel_nest", "kaasmijn_kluis": "kaasmijn",
                  "kaasmijn_schat": "kaasmijn", "knabbelkelder_bieb": "knabbelkelder", "knabbelkelder_cel": "knabbelkelder",
                  "knabbelkelder_gang": "knabbelkelder", "knabbelschat": None, "knabbelvlotje": None, "onderwater_wrak": "onderwater",
                  "spiesburcht_tuintje": "spiesburcht", "vetschip": "mika_vesting", "voorraadschuur": None,
                  "zwevende_eilanden_wolkenkist": "zwevende_eilanden"}
LOOT_LABEL = {"knabbelschat": ("Knabbelschat (Guheinde)", "Knabbel treasure (Guheinde)", "dimensies/guheinde"),
              "knabbelvlotje": ("Knabbelvlotje", "Knabbel raft", None), "voorraadschuur": ("Voorraadschuur", "Storage barn", None)}

# --- where the knowledge-base chunks go ---------------------------------------------------------------------------------------
DROP = "-"
# (section, English title) -> page (DROP: leave out). Checked first.
CHUNK_RULES = {
    ("new30", "New in 3.0: Guhverhalen"): DROP, ("new30", "Baltoguh, Guhtwo and 626-guh"): "systemen/verhaalguhs",
    ("new30", "Home with you"): "systemen/verhaalguhs", ("new30", "The sledesprint against Steele-Mika"): "minigames/sledesprint",
    ("new30", "Steele-Mika before the story"): "minigames/sledesprint", ("new30", "The sprint panel"): "minigames/sledesprint",
    ("new30", "Your own sneeuwslee"): "items/sneeuwslee", ("new30", "The hula dance"): "minigames/hula", ("new30", "Pick a song"): "minigames/hula",
    ("new30", "The Tiki shop"): "npcs/tikiguh", ("new30", "Tikiguh's Tiki shop"): "npcs/tikiguh",
    ("new30", "I &middot; Sixteen new clothes"): DROP, ("new30", "Nomguh from above"): "bouwwerken/nomguh",
    ("fixes2101", "2.10.1: small fixes"): DROP, ("new210", "New in 2.10: Lieve vadsjes van elkaar"): DROP,
    ("fixes210", "Fixes in 2.10"): DROP, ("fixes210", "The land meets every building"): DROP,
    ("fixes210", "Guh-Circuit: no more <i>Oepsie!</i> loop"): DROP, ("fixes210", "The course"): "minigames/golf",
    ("new29", "New in 2.9: De Grote Guhspelen"): DROP, ("new29", "Seven new game guhs"): "minigames/index",
    ("new29", "The superkompas"): "systemen/superkompas", ("new29", "The Heg-Mika"): "wezens/doolhof_mika",
    ("new29", "Levels"): "minigames/circuit", ("new29", "The beroepen guhs"): "verhalen/beroepen",
    ("new29", "Sleepy eyes"): "guhs/normal", ("new29", "Three new Mikas, all harmless"): "wezens/knabbeldief_mika",
    ("new29", "Dressed up"): "guhs/pinguh", ("new29", "Klassiek, keizer and pluis"): "guhs/pinguh",
    ("new281", "New in 2.8.1: Piep!"): DROP, ("new281", "The Boze Oppernabbel"): "wezens/boze_oppernabbel",
    ("new281", "Face to face"): "wezens/boze_oppernabbel", ("new281", "Spot the difference"): "diertjes/poepschilly",
    ("new28", "New in 2.8: Het Knuffeldal"): DROP, ("new28", "Burgemeester Vadsema and the six feesttaakjes"): "verhalen/knusfeest",
    ("new28", "Cocotje"): "npcs/cocotje", ("new28", "De Knabbelbakkerij"): "minigames/bakkerij",
    ("new28", "Het Knabbelthee-huisje"): "npcs/theeguh", ("new28", "Knip &amp; Vads, the hairdresser"): "minigames/kapper",
    ("new28", "The eight hairstyles"): "minigames/kapper", ("new28", "Hair dyes"): "minigames/kapper",
    ("new28", "De Knuffelcreche"): "minigames/creche", ("new28", "The babyguhtjes"): "minigames/creche",
    ("new28", "Het Knuffelbad"): "minigames/glijbanen", ("new28", "Badeendjes"): "bouwwerken/knuffelbad",
    ("new28", "The zwembandje"): "bouwwerken/knuffelbad", ("new28", "Guhkoe, guhschaapje, knabbelkippetje"): "bouwwerken/guhboerderij",
    ("new28", "Guh-luchtballonnen"): "bouwwerken/ballonfestival", ("new28", "The 21 plushies"): "systemen/knuffels",
    ("new28", "Eleven new guh characters"): "bouwwerken/knuffeldal_stadje", ("new28", "The day rhythm"): "systemen/seizoenen",
    ("new28", "Pyjamas"): "kleding/set-kamperen",
    ("new27", "New in 2.7: De Guhbarbecuether en een levendiger Guhmensie"): DROP, ("new27", "The Grillguh's questline"): "verhalen/grillguh",
    ("new27", "The grillkool portal"): "dimensies/barbecuether", ("new27", "Calling him"): "wezens/aangebrande_mika",
    ("new27", "Guh families"): "biomen/vadswoud", ("new27", "The treehouse village"): "bouwwerken/boomhutdorp",
    ("new27", "All new recipes"): DROP,
    ("new26", "The Guheinde and the Knabbelberg"): "dimensies/guheinde", ("new26", "The rewards"): "verhalen/guheinde",
    ("new26", "Two new Guhdex pages"): DROP, ("new26", "New in 2.6: Het Guheinde"): "verhalen/guheinde",
    ("new25", "Guh events"): "systemen/evenementen", ("new25", "Guh emotes"): "systemen/emotes",
    ("new24", "New in 2.4: seven minigames"): "minigames/index", ("new24", "Guh Beauty: the Vads Contest"): "minigames/beauty",
    ("new24", "Guhrace"): "minigames/race", ("new24", "Mika Whacking"): "minigames/meppen", ("new24", "Guhdisco"): "minigames/disco",
    ("new24", "Guhgolf"): "minigames/golf", ("new24", "The Vadsig Food Festival"): "minigames/smul",
    ("new24", "The Guhfish Contest"): "minigames/vissen",
    ("new23", "Guh paintings: the Guh Pile"): "bouwwerken/guh_kasteel", ("new23", "The Koningguh"): "guhs/koning",
    ("new22", "Playing verstopguh"): "minigames/verstopguh", ("new22", "New in 2.2: verstopguh"): "bouwwerken/verstopguh_huis",
    ("new21", "The guh kermis"): "minigames/kermis", ("new21", "New in 2.1: the guh kermis and the ender guh"): "minigames/kermis",
    ("new21", "The sled's buttons"): "systemen/guhslee", ("new21", "Vadsdrop"): "minigames/kermis",
    ("new21", "Guhkurkentrekker"): "minigames/kermis", ("new21", "Vahoegschans"): "minigames/kermis",
    ("mobs", "Giant and mega guhs"): "guhs/normal", ("mobs", "Big Mika (boss)"): "wezens/big_mika", ("mobs", "Hungry Guh"): "npcs/quest_guh",
    ("mobs", "Guh"): "guhs/normal", ("mobs", "Guh variants"): "guhs/index",
    ("care", "Taming, riding and picking up"): "systemen/temmen", ("care", "Launch! (riding)"): "systemen/temmen",
    ("care", "Guh backpack"): "kleding/guh_backpack", ("care", "Iron"): "items/iron_guh_armor", ("care", "Diamond"): "items/diamond_guh_armor",
    ("care", "Netherite"): "items/netherite_guh_armor", ("care", "Guh armour"): "systemen/temmen",
    ("care", "The Guh menu (hold right-click on your guh)"): "systemen/guhmenu", ("care", "Guh clothes and the wardrobe"): "systemen/kleding",
    ("maag", "Your own guh stomach"): "dimensies/guhmaag", ("maag", "1. Mother Vadsig"): "verhalen/moeder-vadsig",
    ("maag", "2. The Mika camp"): "verhalen/moeder-vadsig", ("maag", "3. The lost cake"): "verhalen/moeder-vadsig",
    ("maag", "4. The party"): "verhalen/moeder-vadsig", ("maag", "Getting around"): "dimensies/guhmaag",
    ("sled", "Quest: the broken sled"): "verhalen/kapotte-slee", ("sled", "The guh sled"): "systemen/guhslee",
    ("items", "Bank Guh"): "items/bank_guh", ("items", "Kaasknabbel ores"): "blokken/kaasknabbel_stone",
    ("items", "Mika trail compass &amp; cake crumbs"): "items/mika_spoorkompas",
    ("guhmension", "Guh crystal mines"): "biomen/guh_kristalmijn", ("guhmension", "Biomes"): "biomen/index",
    ("guhmension", "Pink grass and flowers"): "dimensies/guhmension",
    ("villages", "Guh villages"): "bouwwerken/guh_village", ("villages", "Mika-mepper"): "items/mika_mepper",
    ("more", "Advancements and commands"): "systemen/vooruitgangen",
    ("fixes2101", "The Guhkamer button"): "systemen/guhkamer",
}
# (section or "*", start of the h3 title) -> page, checked after the pictures
H3_RULES = [
    ("new30", "Where are the stories", "systemen/superkompas"), ("new30", "The story guhs", "systemen/verhaalguhs"),
    ("new30", "A &middot; De Timmerguh", "verhalen/timmerguh"), ("new30", "B &middot; Baltoguh", "bouwwerken/nomguh"),
    ("new30", "The characters of Nomguh", "verhalen/nomguh"), ("new30", "C &middot; De slee", "verhalen/sneeuwstorm"),
    ("new30", "D &middot; Het kloon-eiland", "verhalen/kloon-eiland"), ("new30", "E &middot; Het Hemelkapelletje", "verhalen/hemelkapelletje"),
    ("new30", "F &middot; Guhwai", "verhalen/ohana"), ("new30", "G &middot; Surfen", "minigames/surfen"),
    ("new30", "H &middot; Diertjes", "diertjes/index"), ("new30", "The Guhdex", "systemen/guhdex"),
    ("fixes2101", "The guh menu", "systemen/guhmenu"), ("fixes2101", "Moeder Vadsig", "verhalen/moeder-vadsig"),
    ("fixes2101", "More elfstempels", "minigames/elftocht"), ("fixes2101", "Guh-sneeuw", "biomen/guhpolder"),
    ("new210", "A &middot; De hartjesmeter", "systemen/hartjes"), ("new210", "The zielsguh", "systemen/hartjes"),
    ("new210", "Four new emotes", "systemen/emotes"), ("new210", "B &middot; Favorietjes", "systemen/favorietjes"),
    ("new210", "Blij", "systemen/favorietjes"), ("new210", "C &middot; Het Guhhuisje", "systemen/guhhuisje"),
    ("new210", "The huisje screen", "systemen/guhhuisje"), ("new210", "D &middot; Tien klusjes", "systemen/klusjes"),
    ("new210", "E &middot; Speelgoed", "systemen/speelgoed"), ("new210", "F &middot; Samen", "systemen/samen"),
    ("new210", "G &middot; De Guhdex", "systemen/guhdex"), ("new210", "H &middot; De Guhkamer", "systemen/guhkamer"),
    ("new210", "The guh menu", "systemen/guhmenu"),
    ("fixes210", "Guhgolf", "minigames/golf"), ("fixes210", "Guhdoolhof", "minigames/doolhof"),
    ("fixes210", "Names and the Guhdex", "systemen/guhdex"), ("fixes210", "The Elf-Guhjestocht", "bouwwerken/elfguhjestocht"),
    ("new29", "A &middot; Het Sjoelhuisje", "minigames/sjoelen"), ("new29", "B &middot; Het Guhdoolhof", "minigames/doolhof"),
    ("new29", "C &middot; De Knabbelkatapult", "minigames/katapult"), ("new29", "D &middot; De Knabbelspelen", "minigames/knabbelspelen"),
    ("new29", "De Guhpolder", "biomen/guhpolder"), ("new29", "E &middot; De Elf-Guhjestocht", "minigames/elftocht"),
    ("new29", "F &middot; Het Guh-Circuit", "minigames/circuit"), ("new29", "G &middot; Makkelijk", "systemen/moeilijkheid"),
    ("new29", "The Guhdisco", "minigames/disco"), ("new29", "I &middot; Clothes", "systemen/kleding"),
    ("new29", "H &middot; The Guhdex", "systemen/guhdex"), ("new29", "J &middot; Beroepen", "verhalen/beroepen"),
    ("new29", "Piep: little menus", "diertjes/pieppiepmuisje"),
    ("new281", "The pieppiepmuisje", "diertjes/pieppiepmuisje"), ("new281", "Two turtles", "diertjes/poepschilly"),
    ("new281", "The Roze Guh Koek", "items/roze_guh_koek"), ("new281", "The kaasknabbel-nest", "bouwwerken/kaasknabbel_nest"),
    ("new281", "Guhdex: Piep", "systemen/guhdex"),
    ("new28", "Het Knuffeldal", "bouwwerken/knuffeldal_stadje"), ("new28", "Het Grote Knusfeest", "verhalen/knusfeest"),
    ("new28", "Seasons", "systemen/seizoenen"), ("new28", "On the plein", "bouwwerken/knuffeldal_stadje"),
    ("new28", "Outside the town", "bouwwerken/knuffeldal_stadje"), ("new28", "Everywhere in the Guhmension", "dimensies/guhmension"),
    ("new28", "The Guhdex: tab Knus", "systemen/guhdex"),
    ("new27", "De Guhbarbecuether", "dimensies/barbecuether"), ("new27", "De Spiesburcht", "dimensies/barbecuether"),
    ("new27", "The Guhbrouwketel", "systemen/brouwen"), ("new27", "The Knabbelbaken", "blokken/knabbelbaken"),
    ("new27", "De Gatenkaasgrotten", "biomen/gatenkaasgrotten"), ("new27", "Het Kaasmoeras", "biomen/kaasmoeras"),
    ("new27", "Het Vadswoud", "biomen/vadswoud"), ("new27", "De Diepe Guhzee", "biomen/diepe_guhzee"),
    ("new27", "Minigames and the Guhdex", "systemen/guhdex"), ("new27", "Boss: the Aangebrande Mika", "wezens/aangebrande_mika"),
    ("sled", "Building a track", "systemen/guhslee"),
    ("*", "Handy commands", "systemen/commandos"), ("*", "Advancements", DROP), ("*", "FTB quests", DROP), ("*", "Some recipes", DROP),
]
# section -> page, the last resort
SECTION_RULES = {
    "start": "index", "new26": "verhalen/guheinde", "new21": "minigames/kermis", "personalities": "systemen/karakters",
    "care": "systemen/temmen", "maag": "dimensies/guhmaag", "sled": "systemen/guhslee", "guhdex": "systemen/guhdex",
    "vads": "systemen/vahoege-vads", "redstone": DROP, "guhmension": "dimensies/guhmension", "villages": "bouwwerken/guh_village",
    "reizen": "systemen/superkompas", "more": "systemen/vooruitgangen", "food": DROP, "items": DROP, "structures": DROP,
    "recipes": DROP, "new22": "minigames/verstopguh", "new23": "bouwwerken/guh_kasteel", "rare24": DROP, "new24": DROP,
    "new25": DROP, "mobs": DROP,
}
