"""
Baltoguh en Nomguh (3.0 Guhverhalen, slice balto) - every text in the game (Dutch, en_us gets the same): the blocks and
items, the characters and their Guhdex pages, the scenes of the questline, the chat lines, the Baltoguh's sniffing, the
advancements. Short balloons (the talking screen shows ~6 lines of ~32 letters), lots of njeg / vads / VAHOEG, Boris with
his goose accent ("Da, kleine guh... gak!"), Steele-Mika boasting ("njeh-heh"), Luk never says a word.
"""

TEKSTEN = {
    # --- blocks, items ----------------------------------------------------------------------------------------------------------
    "block.guhs.baltoguh_beeldje": "Baltoguh-beeldje",
    "block.guhs.baltoguh_beeldje.lore": "Een bronzen Baltoguh op een besneeuwde sokkel. Voor de Held van Nomguh. Klik: auuuhoe!",
    "block.guhs.baltoguh_beeldje.klik": "\"...Maar heel misschien... een Baltoguh wel.\" Auuuhoe-njeg!",
    "block.guhs.nomguh_routepaal": "Routepaaltje",
    "block.guhs.nomguh_routepaal.lore": "Rood-wit, met een gloeiend guhoortje erop: zo verdwaal je nooit in de sneeuwstorm.",
    "block.guhs.nomguh_sneeuwspoor": "Sledespoorsneeuw",
    "block.guhs.nomguh_sneeuwdak": "Besneeuwde dakpannen",
    "block.guhs.nomguh_sneeuwdak_trap": "Besneeuwde daktrap",
    "block.guhs.nomguh_sneeuwdak_plaat": "Besneeuwde dakplaat",
    "block.guhs.nomguh_medicijnkist": "Medicijnkist",
    "block.guhs.nomguh_medicijnkist.lore": "Het medicijn voor de guhbaby's van Nomguh. Zuinig op zijn, njeg!",
    "block.guhs.sneeuwguhspar_stam": "Sneeuwguhsparstam",
    "block.guhs.sneeuwguhspar_gezicht": "Slaperige sneeuwguhspar",
    "block.guhs.sneeuwguhspar_naalden": "Sneeuwguhsparnaalden",
    "block.guhs.sneeuwguhspar_zaailing": "Sneeuwguhsparzaailing",
    "block.guhs.sneeuwguhspar_zaailing.lore": "Een piepklein sparretje met een sneeuwmutsje. Groeit uit tot een echte sneeuwguhspar!",
    "item.guhs.balto_sjaaltje": "Rood sjaaltje van Baltoguh",
    "item.guhs.balto_wolfsoortjes": "Wolfsoortjes",
    "item.guhs.balto_sneeuwmuts": "Sneeuwmuts met pompon",
    "item.guhs.balto_wantjes": "Wantjes aan een touwtje",
    "subtitles.guhs.balto.huil": "Baltoguh huilt: auuuhoe-njeg!",
    "subtitles.guhs.balto.gak": "Boris: gak!",
    "subtitles.guhs.balto.belletjes": "Sledebelletjes rinkelen",
    "subtitles.guhs.balto.hatsjoe": "Hatsjoe-njeg!",
    "subtitles.guhs.balto.snuffel": "Baltoguh snuffelt",
    "subtitles.guhs.balto.wind": "De sneeuwstorm waait",
    "structure.guhs.nomguh": "Nomguh",
    "structure.guhs.nomguh.tooltip": "Het besneeuwde guhstadje midden in de Sneeuwguhtoendra: Baltoguh, Boris, Rosy en de tocht door de storm",
    "gui.guhs.balto.niet_bouwen": "Nomguh is zo mooi besneeuwd, njeg! Hier bouw of breek je niks.",
    "gui.guhs.balto.titel": "Held van Nomguh",
    "gui.guhs.balto.verteller": "Verteller",
    "gui.guhs.balto.zuster": "Zuster Knuffel",
    "gui.guhs.balto.boris_gedachten": "Boris (in gedachten)",
    "gui.guhs.verhaal.kopie.baltoguh": "Snuf snuf... ruik jij dat ook? Sneeuw. Heel veel sneeuw. Njeg.",

    # --- the characters: names and Guhdex pages ----------------------------------------------------------------------------------
    "entity.guhs.guh.baltoguh": "Baltoguh",
    "entity.guhs.baltoguh": "Baltoguh",
    "gui.guhs.guhdex.rarity.baltoguh": "Zeldzaamheid: Eén per speler, na het verhaal van Nomguh",
    "gui.guhs.guhdex.info.baltoguh": "Half guh, half wolf: een grijze vacht, spitse wolfsoortjes, een lichte buik en een echte guhsnoet. "
                                     "Vroeger een beetje een buitenbeentje, nu de held van Nomguh. In de sneeuw rent hij supervahoeg "
                                     "(ook als je op hem rijdt), en met de knop Snuffel! in het guhmenu ruikt hij de weg naar je huisje "
                                     "of je spawnpunt: volg de gloeiende pootjes! Njeg.",
    "entity.guhs.guh_npc.boris": "Boris",
    "gui.guhs.guhdex.rarity.boris": "Zeldzaamheid: Eén, op de oude boot van Nomguh",
    "gui.guhs.guhdex.info.boris": "Een echte gans (geen guh!) met een bontmutsje en een Russisch accent. Da, kleine guh... gak! Hij woont "
                                  "met Baltoguh op de oude boot in de bevroren baai en weet altijd raad. Zijn wijsheid: een guh denkt niet "
                                  "alleen met zijn pootjes, maar ook met zijn hartje.",
    "entity.guhs.guh_npc.steele_mika": "Steele-Mika",
    "gui.guhs.guhdex.rarity.steele_mika": "Zeldzaamheid: Eén, bij de startlijn van Nomguh",
    "gui.guhs.guhdex.info.steele_mika": "De opschepperige kampioen-sledeleider van Nomguh, met een rood racepetje, een stofbril en een "
                                        "gouden medaille. IK ben de snelste, njeh-heh! Hij wil altijd de eer, maar iedereen lacht hem lief uit. "
                                        "Na het verhaal kun je tegen hem racen over de route.",
    "entity.guhs.guh_npc.muk": "Muk",
    "gui.guhs.guhdex.rarity.muk": "Zeldzaamheid: Eén, bij de iglo van Nomguh",
    "gui.guhs.guhdex.info.muk": "Een grote, lieve ijsbeer-guh met een blauwe sjaal. Muk praat voor twee (want Luk zegt nooit iets) en "
                                "vist graag in het ijsvijvertje. Knuffels zijn gratis!",
    "entity.guhs.guh_npc.luk": "Luk",
    "gui.guhs.guhdex.rarity.luk": "Zeldzaamheid: Eén, bij de iglo van Nomguh",
    "gui.guhs.guhdex.info.luk": "Een grote, lieve ijsbeer-guh met een groene sjaal en een hengeltje. Luk zegt nooit iets, maar knikt, "
                                "zwaait en knuffelt des te meer. Muk vertaalt.",
    "entity.guhs.guh_npc.rosy": "Rosy",
    "gui.guhs.guhdex.rarity.rosy": "Zeldzaamheid: Eén, in het ziekenhuisje van Nomguh",
    "gui.guhs.guhdex.info.rosy": "Een klein roze babyguhtje in een bedje, met een geel sjaaltje en een rood neusje. Ze had de knabbelkuch "
                                 "en niesde heel schattig (hatsjoe-njeg!). Dankzij de medicijnkist uit de berghut is ze weer helemaal beter.",
    "entity.guhs.guh_npc.witte_wolfguh": "De witte wolf-guh",
    "entity.guhs.witte_wolfguh": "De witte wolf-guh",
    "gui.guhs.guhdex.rarity.witte_wolfguh": "Zeldzaamheid: Alleen op het dieptepunt van de tocht",
    "gui.guhs.guhdex.info.witte_wolfguh": "Een witte wolf-guh die zachtjes gloeit, als een sterretje in de sneeuw. Ze verschijnt alleen "
                                          "als het het donkerst is, en kijkt je heel lief aan. Daarna is ze weg... maar je vergeet haar nooit.",

    # --- chat lines ----------------------------------------------------------------------------------------------------------------
    "gui.guhs.balto.balto.naar_rosy": "Ga maar naar Rosy in het ziekenhuisje: het witte huis met het roze hartje. Ik ruik dat ze niest, njeg.",
    "gui.guhs.balto.balto.naar_boris": "Boris weet altijd raad. Hij zit op onze boot, hier vlakbij. Gak, zegt hij dan.",
    "gui.guhs.balto.balto.onderweg": "Hup hup! We zijn onderweg, volg de rode paaltjes!",
    "gui.guhs.balto.balto.naar_rosy_kist": "Snel, breng de medicijnkist naar Rosy! Ik ren mee, njeg!",
    "gui.guhs.balto.balto.klaar.0": "Iedereen noemt me nu een held. Ik ben gewoon... Baltoguh. Maar wel een VAHOEGE, njeg!",
    "gui.guhs.balto.balto.klaar.1": "Ruik je dat? Warme chocomelk op het plein. Njeg!",
    "gui.guhs.balto.balto.klaar.2": "Half guh, half wolf. Helemaal goed zo.",
    "gui.guhs.balto.balto.na_temmen.0": "Hoe gaat het met de Baltoguh bij jou thuis? Aai hem van me, njeg!",
    "gui.guhs.balto.balto.na_temmen.1": "Ik blijf hier op de boot, bij Boris. Maar jij bent altijd welkom!",
    "gui.guhs.balto.balto.na_temmen.2": "Auuuhoe! (dat betekent: hoi!)",
    "gui.guhs.balto.boris.nieuw": "Gak! Een nieuw gezicht! Ga eens hallo zeggen tegen Baltoguh, da? Hij zit daar op het ijs.",
    "gui.guhs.balto.boris.eerst_rosy": "Rosy is ziek, ja? Kijk eerst bij haar in het ziekenhuisje, kleine guh. Dan praten we. Gak.",
    "gui.guhs.balto.boris.ga": "Waar wacht je op? Baltoguh staat klaar bij de boot. Gak gak!",
    "gui.guhs.balto.boris.onderweg": "Gak! Onderweg, onderweg! Volg de paaltjes, da?",
    "gui.guhs.balto.boris.naar_rosy": "Niet naar mij, naar Rosy met die kist! Gak!",
    "gui.guhs.balto.boris.klaar.0": "Da, ik zei het toch? Maar heel misschien... een Baltoguh wel. Gak!",
    "gui.guhs.balto.boris.klaar.1": "Wil je vliegles? Grapje, gak. Ik vlieg zelf ook bijna nooit.",
    "gui.guhs.balto.boris.klaar.2": "Een gans heeft altijd koude voetjes. Daarom sta ik op één poot. Gak.",
    "gui.guhs.balto.boris.klaar.3": "Mijn mutsje? Van mijn oma. Uit het verre oosten, da.",
    "gui.guhs.balto.steele.begin.0": "Njeh-heh! IK ben Steele-Mika, de snelste sledeleider van heel Nomguh. En jij bent... niemand.",
    "gui.guhs.balto.steele.begin.1": "Dat wolvenguhtje? Die trekt nog geen sleetje met knabbels. Njeh-heh!",
    "gui.guhs.balto.steele.begin.2": "Zie je mijn medaille? Goud. Net als mijn vacht. Nou ja, bijna.",
    "gui.guhs.balto.steele.storm": "Naar de berghut? In DEZE storm? Mijn prachtige vacht wordt nat, njeh. Doe jij het maar.",
    "gui.guhs.balto.steele.onderweg": "Ik zou natuurlijk veel sneller zijn. Maar ik moest mijn vacht borstelen.",
    "gui.guhs.balto.steele.eer": "Eh... de kist? Die heb IK natuurlijk... nou ja. Ga maar. Snel.",
    "gui.guhs.balto.steele.klaar.0": "Hmpf. Ik had het ook gekund, njeh-heh. Maar ik had het druk. Met mijn vacht.",
    "gui.guhs.balto.steele.klaar.1": "Zullen we racen? Dan zie je wie echt de snelste is! (Njeh.)",
    "gui.guhs.balto.steele.klaar.2": "Die Baltoguh... ach, hij is best oké. Zeg het tegen niemand.",
    "gui.guhs.balto.muk.0": "Hoi! Ik ben Muk, en dat is Luk. Luk zegt: hoi! (Luk zwaait.)",
    "gui.guhs.balto.muk.1": "Wij vissen hier guh-visjes uit het ijs. Luk vangt er meer, maar ik tel beter!",
    "gui.guhs.balto.muk.2": "Brrr? Nee hoor, wij hebben het nooit koud. Wij zijn ijsbeer-guhs! Knuffel?",
    "gui.guhs.balto.muk.klaar.0": "Je bent een held! Luk vindt dat ook. (Luk knikt heel hard.)",
    "gui.guhs.balto.muk.klaar.1": "Rosy is weer beter! Luk heeft gehuild van blijdschap. Ik ook een beetje.",
    "gui.guhs.balto.muk.klaar.2": "Kom je een keer ijsvissen? Luk leent je zijn hengeltje!",
    "gui.guhs.balto.luk.0": "(Luk zwaait naar je, heel breed.)",
    "gui.guhs.balto.luk.1": "(Luk knikt. Daarna knikt hij nog een keer, voor de zekerheid.)",
    "gui.guhs.balto.luk.2": "(Luk geeft je een dikke ijsbeer-knuffel. Warm!)",
    "gui.guhs.balto.luk.3": "(Luk laat je trots zijn hengeltje zien. Er hangt een sokje aan.)",
    "gui.guhs.balto.rosy.nieuw": "Hatsjoe! Oh, hoi. Wie ben jij? Ben jij een vriendje van Baltoguh? Hatsjoe-njeg!",
    "gui.guhs.balto.rosy.wachten.0": "Hatsjoe! Kom je snel terug met het medicijn? Ik wacht hier. In mijn bedje. Njeg.",
    "gui.guhs.balto.rosy.wachten.1": "Zuster Knuffel zegt dat ik dapper ben. Hatsjoe! Ben jij ook dapper?",
    "gui.guhs.balto.rosy.beter.0": "Ik ben weer helemaal beter! Mag ik op je schouders? VAHOEG!",
    "gui.guhs.balto.rosy.beter.1": "Als ik groot ben, word ik sledeguh. Net als Baltoguh!",
    "gui.guhs.balto.rosy.beter.2": "Mijn neusje doet het weer: ik ruik chocomelk! Njeg!",
    "gui.guhs.balto.wolf.0": "(De witte wolf-guh kijkt je zacht aan. Je hart wordt er warm van.)",
    "gui.guhs.balto.wolf.1": "(Ze zegt niets. Maar je weet precies wat ze bedoelt.)",
    "gui.guhs.balto.wolf.2": "(Sneeuwvlokjes dansen om haar heen, als sterretjes.)",
    "gui.guhs.balto.slee_niet": "Njeg... de slee kan nu niet vertrekken (ben je nog bezig, of is er geen Nomguh vlakbij?).",
    "gui.guhs.balto.moment.start": "Hup, Baltoguh! De tocht naar de berghut begint. Volg de rode paaltjes met de lampjes!",
    "gui.guhs.balto.moment.te_laat": "Njeg, nog een keer! Te laat... maar Rosy is dapper en wacht nog even. Probeer het opnieuw!",
    "gui.guhs.balto.moment.gestopt": "De tocht is gestopt. Baltoguh wacht op je bij de oude boot. Zullen we het nog eens proberen?",
    "gui.guhs.balto.moment.storm_klaart_op": "De storm klaart op... Baltoguh weet de weg weer! VAHOEG!",
    "gui.guhs.balto.held": "✿ %s is de Held van Nomguh! Rosy is beter, en alle guhs zingen. VAHOEG!",
    "gui.guhs.balto.getemd": "Baltoguh gaat met je mee! Hij ruikt de weg naar je huisje: druk in zijn guhmenu op Snuffel!",
    "gui.guhs.balto.hint.rosy": "Ga naar Rosy in het ziekenhuisje van Nomguh (het witte huis met het roze hart)",
    "gui.guhs.balto.hint.boris": "Vraag Boris om raad: de gans op de oude boot in de bevroren baai",
    "gui.guhs.balto.hint.start": "Praat met Baltoguh bij de oude boot: op naar de berghut!",
    "gui.guhs.balto.hint.kist": "Breng de medicijnkist naar Rosy in het ziekenhuisje",
    "gui.guhs.balto.hint.tem": "Baltoguh wil met je mee: praat met hem bij de oude boot",

    # --- the scenes ---------------------------------------------------------------------------------------------------------------
    "gui.guhs.balto.scene.ontmoet.1": "Bij een oude boot op het ijs zit een grijze guh met spitse wolfsoortjes. Hij kijkt een beetje verlegen.",
    "gui.guhs.balto.scene.ontmoet.2": "Oh! Hoi... Ik ben Baltoguh. Half guh, half wolf. De andere guhs vinden me een beetje... raar. Njeg.",
    "gui.guhs.balto.scene.ontmoet.3": "Njeh-heh! Kijk eens, het wolvenguhtje! In Nomguh trekken alleen ECHTE sledeguhs de slee. Zoals IK!",
    "gui.guhs.balto.scene.ontmoet.4": "...Hij bedoelt het vast niet zo. Denk ik. Maar weet je? Er is iets mis in het ziekenhuisje. Ik ruik het.",
    "gui.guhs.balto.scene.ontmoet.5": "De guhbaby's zijn ziek, en Rosy het meest. Wil jij bij haar gaan kijken? Het is het witte huis met het roze hart.",
    "gui.guhs.balto.optie.ontmoet": "Natuurlijk! Ik ga naar Rosy.",
    "gui.guhs.balto.scene.rosy.1": "In het ziekenhuisje liggen de guhbaby's in hun wiegjes. Ze snotteren zachtjes. Bij het raam ligt Rosy.",
    "gui.guhs.balto.scene.rosy.2": "Hatsjoe-njeg! Oh, hoi! Ik ben Rosy. Ik heb de knabbelkuch... Mijn neusje is helemaal rood.",
    "gui.guhs.balto.scene.rosy.3": "Het medicijn is op, njeg. De nieuwe medicijnkist ligt in de berghut, hoog op de Nomguhpieken. En er komt een sneeuwstorm aan...",
    "gui.guhs.balto.scene.rosy.4": "Wil jij hem halen? Dan word ik weer beter en kan ik weer sleetje rijden! Hatsjoe!",
    "gui.guhs.balto.scene.rosy.5": "Wie weet de weg door de storm? Misschien Boris, de gans op de oude boot. Hij weet altijd raad.",
    "gui.guhs.balto.optie.rosy": "Ik haal het medicijn, Rosy!",
    "gui.guhs.balto.scene.boris.1": "Gak! Da, kleine guh... Rosy is ziek, ja? Ik hoorde het al. Mijn veren gingen er rechtop van staan.",
    "gui.guhs.balto.scene.boris.2": "Luister goed. De weg naar de berghut is gemarkeerd met rode paaltjes met een lampje. Volg de paaltjes, da?",
    "gui.guhs.balto.scene.boris.3": "Onderweg: het Stormdal, de IJsbrug over de Kloof en de Lawineberg. Blijf in het midden, en rust bij de vuurkorven.",
    "gui.guhs.balto.scene.boris.4": "En neem Baltoguh mee. Iedereen denkt dat hij maar een halve guh is... maar zijn neus is de beste van Nomguh.",
    "gui.guhs.balto.scene.boris.5": "Onthoud: een guh denkt niet alleen met zijn pootjes, maar ook met zijn hartje. Gak gak!",
    "gui.guhs.balto.optie.boris": "Dank je, Boris!",
    "gui.guhs.balto.scene.start.1": "Boris heeft het je verteld, hè? Ik trek de slee, jij stuurt. Samen halen we het medicijn voor Rosy!",
    "gui.guhs.balto.optie.start": "Op naar de berghut!",
    "gui.guhs.balto.optie.nog_niet": "Nog heel even...",
    "gui.guhs.balto.scene.berghut.1": "De berghut! Binnen is het lekker warm. Op tafel staat de medicijnkist, met een roze hartje op het deksel.",
    "gui.guhs.balto.scene.berghut.2": "Snuf snuf... dit is hem! Hou hem goed vast. Nu snel terug naar Rosy, voordat de storm nog erger wordt!",
    "gui.guhs.balto.optie.berghut": "Pak de medicijnkist en ga terug!",
    "gui.guhs.balto.scene.wolf.1": "De storm is te erg. Je ziet de paaltjes niet meer. Baltoguh snuffelt... maar hij ruikt alleen sneeuw. Hij is de weg kwijt. Njeg...",
    "gui.guhs.balto.scene.wolf.2": "Ik... ik weet het niet meer. Misschien hebben ze gelijk. Misschien ben ik maar een halve guh.",
    "gui.guhs.balto.scene.wolf.3": "Dan staat er ineens een witte wolf-guh tussen de sneeuwvlokken. Ze gloeit zachtjes, als een sterretje, en kijkt Baltoguh heel lief aan.",
    "gui.guhs.balto.scene.wolf.4": "Een gewone guh kan deze tocht niet alleen volbrengen...",
    "gui.guhs.balto.scene.wolf.5": "Maar heel misschien... een Baltoguh wel.",
    "gui.guhs.balto.scene.wolf.6": "Ik ben half guh... én half wolf. En dat is precies goed. AUUUHOE-NJEG!",
    "gui.guhs.balto.optie.huil": "Huil mee met Baltoguh!",
    "gui.guhs.balto.scene.aankomst.1": "Daar is Nomguh! Alle lichtjes branden. De guhs staan te juichen bij de stal.",
    "gui.guhs.balto.scene.aankomst.2": "Eh... ja! Goed gedaan, hoor. IK heb ze natuurlijk de weg gewezen. Met mijn... eh... prachtige vacht. Njeh-heh?",
    "gui.guhs.balto.scene.aankomst.3": "Alle guhs kijken Steele-Mika aan... en dan beginnen ze te giechelen. Hihihi, njeg! Zelfs Steele-Mika moet een beetje lachen.",
    "gui.guhs.balto.scene.aankomst.4": "Nog één stukje! Breng de medicijnkist naar Rosy in het ziekenhuisje!",
    "gui.guhs.balto.scene.feest.1": "Je zet de medicijnkist naast Rosy's bedje. Zuster Knuffel geeft alle guhbaby's een lepeltje knabbelsiroop.",
    "gui.guhs.balto.scene.feest.2": "Mmm, het smaakt naar aardbeien-kaas! ...Hé! Mijn neusje doet het weer! Ik ben beter! VAHOEG!",
    "gui.guhs.balto.scene.feest.3": "Je hebt het gedaan! Nee... WIJ hebben het gedaan. Samen. Njeg!",
    "gui.guhs.balto.scene.feest.4": "Iedereen in Nomguh noemt jou nu de Held van Nomguh. En Baltoguh? Die is nooit meer een buitenbeentje.",
    "gui.guhs.balto.scene.feest.5": "Gak! Wat zei ik je, da? Maar heel misschien... een Baltoguh wel!",
    "gui.guhs.balto.optie.feest": "VAHOEG!",
    "gui.guhs.balto.scene.tem.1": "Weet je... ik wil wel met jou mee. Naar jouw huisje. Mag dat? Ik ruik de weg altijd terug, njeg!",
    "gui.guhs.balto.optie.tem_ja": "Ja! Kom maar mee, Baltoguh!",
    "gui.guhs.balto.optie.tem_nee": "Blijf nog even in Nomguh.",

    # --- the Baltoguh's sniffing (the guh-menu button) -----------------------------------------------------------------------------
    "gui.guhs.balto.snuffel": "Snuffel!",
    "gui.guhs.balto.snuffel.tooltip": "Baltoguh ruikt de weg naar je huisje (of je spawnpunt). Volg de gloeiende pootjes!",
    "gui.guhs.balto.snuffel.huisje": "Snuf snuf! %1$s ruikt je huisje: nog %2$s blokjes naar het %3$s. Volg de pootjes, njeg!",
    "gui.guhs.balto.snuffel.spawn": "Snuf snuf! %1$s ruikt je bed: nog %2$s blokjes naar het %3$s. Volg de pootjes!",
    "gui.guhs.balto.snuffel.al_thuis.huisje": "Snuf... %s kwispelt: je bent al bij je huisje! Njeg.",
    "gui.guhs.balto.snuffel.al_thuis.spawn": "Snuf... %s kwispelt: je bent al thuis! Njeg.",
    "gui.guhs.balto.snuffel.andere_wereld": "Snuf snuf... %s ruikt je thuis wel, maar dat is in een andere wereld. Njeg!",
    "gui.guhs.balto.richting.noorden": "noorden",
    "gui.guhs.balto.richting.noordoosten": "noordoosten",
    "gui.guhs.balto.richting.oosten": "oosten",
    "gui.guhs.balto.richting.zuidoosten": "zuidoosten",
    "gui.guhs.balto.richting.zuiden": "zuiden",
    "gui.guhs.balto.richting.zuidwesten": "zuidwesten",
    "gui.guhs.balto.richting.westen": "westen",
    "gui.guhs.balto.richting.noordwesten": "noordwesten",
}

# the shown advancements (tab guhs:verhalen/): name, parent, icon, frame, title, description, criteria (None = granted by code)
ADVANCEMENTS = [
    ("balto_nomguh", "verhaal_toendra", "guhs:nomguh_routepaal", "task", "Brrr, Nomguh!",
     "Vind Nomguh, het besneeuwde guhstadje midden in de Sneeuwguhtoendra",
     {"done": {"trigger": "minecraft:location", "conditions": {"player": {"location": {"structures": "guhs:nomguh"}}}}}),
    ("balto_ontmoet", "balto_nomguh", "minecraft:snowball", "task", "Een buitenbeentje", "Maak kennis met Baltoguh bij de oude boot", None),
    ("balto_rosy", "balto_ontmoet", "guhs:nomguh_medicijnkist", "task", "Hatsjoe-njeg!", "Bezoek Rosy en de zieke guhbaby's in het ziekenhuisje", None),
    ("balto_boris", "balto_rosy", "minecraft:feather", "task", "Da, kleine guh... gak!", "Vraag Boris de gans om raad", None),
    ("balto_mukluk", "balto_nomguh", "minecraft:cod", "task", "Muk en Luk", "Zeg hallo tegen allebei de ijsbeer-guhs (Luk zegt niks terug)", None),
    ("balto_tocht", "balto_boris", "guhs:nomguh_routepaal", "task", "Hup, Baltoguh!", "Begin aan de tocht door de sneeuwstorm naar de berghut", None),
    ("balto_berghut", "balto_tocht", "guhs:nomguh_medicijnkist", "goal", "De medicijnkist", "Pak de medicijnkist in de berghut op de Nomguhpieken", None),
    ("balto_wolf", "balto_berghut", "minecraft:glow_berries", "goal", "De witte wolf-guh", "Huil mee met Baltoguh op het dieptepunt van de tocht", None),
    ("balto_aankomst", "balto_wolf", "minecraft:bell", "task", "Op tijd!", "Kom op tijd terug in Nomguh (Steele-Mika wil de eer, iedereen giechelt)", None),
    ("balto_held", "balto_aankomst", "guhs:baltoguh_beeldje", "challenge", "Maar heel misschien... een Baltoguh wel",
     "Breng het medicijn naar Rosy en word de Held van Nomguh", None),
    ("balto_getemd", "balto_held", "minecraft:bone", "goal", "Een eigen Baltoguh", "Neem Baltoguh mee naar huis (eenmalig, alleen voor jou)", None),
    ("balto_snuffel", "balto_getemd", "minecraft:compass", "task", "Snuf snuf, naar huis!", "Laat je Baltoguh de weg naar je huisje ruiken", None),
    ("balto_sneeuwsnel", "balto_getemd", "minecraft:powder_snow_bucket", "task", "Zo snel als de wind", "Rijd op je Baltoguh supervahoeg door de sneeuw", None),
    ("balto_beeldje", "balto_held", "guhs:baltoguh_beeldje", "task", "Een held op een sokkel", "Zet je Baltoguh-beeldje ergens neer",
     {"done": {"trigger": "minecraft:placed_block", "conditions": {"location": [{"condition": "minecraft:block_state_property",
                                                                                  "block": "guhs:baltoguh_beeldje"}]}}}),
    ("balto_outfits", "balto_held", "guhs:balto_sneeuwmuts", "goal", "Warm ingepakt in Nomguh",
     "Ontgrendel het rode sjaaltje, de wolfsoortjes, de sneeuwmuts en de wantjes", None),
]
