"""
3.0 (Guhverhalen), balto_slee - all texts (Dutch, also in en_us): the sled ride, the storm, the sledesprint, Steele-Mika's
lines, the panel, your own sneeuwslee, the items, the advancements.
"""

LANG = {
    # --- the entities and items ---
    "entity.guhs.baltoslee_slee": "Nomguh-slee",
    "entity.guhs.sneeuwslee": "Sneeuwslee",
    "entity.guhs.baltoslee_sledehondje": "Guh-sledehondje",
    "item.guhs.sneeuwslee": "Sneeuwslee",
    "item.guhs.sneeuwslee.lore": "Je eigen slee met vier guh-sledehondjes. Hup, hup, door de sneeuw!",
    "item.guhs.sneeuwslee.lore2": "Zet hem neer op sneeuw of ijs · W: hup hup · S: remmen · A/D: sturen · sluipen + rechtsklik: oppakken",
    "item.guhs.sledebelletje": "Sledebelletje",
    "item.guhs.sledebelletje.lore": "Tingeling! Verdiend bij de Nomguh-sledesprint. Steele-Mika ruilt ze voor winterspulletjes.",
    "block.guhs.baltoslee_sneeuwguh": "Sneeuwguh",
    "item.guhs.baltoslee_sneeuwguh.lore": "Een sneeuwpop, maar dan een guh. Met een wortelsnoetje en een sjaaltje. Brrr-njeg!",
    "block.guhs.baltoslee_minislee": "Minisleetje",
    "item.guhs.baltoslee_minislee.lore": "Een klein sleetje met een rood dekentje. Je kunt erin zitten!",
    "block.guhs.baltoslee_sledebellen": "Sledebellenboog",
    "item.guhs.baltoslee_sledebellen.lore": "Tik erop: tingelingeling! Net als de slee van Nomguh.",
    "block.guhs.baltoslee_beker": "Sledesprintbeker",
    "item.guhs.baltoslee_beker.lore": "De gouden beker van de snelste sledeguh. Met guhoortjes, natuurlijk.",
    "block.guhs.baltoslee_hondenmand": "Sledehondenmandje",
    "item.guhs.baltoslee_hondenmand.lore": "Een warm mandje met een kussentje en een botvormige kaasknabbel. Voor moeie pootjes.",
    "block.guhs.baltoslee_lantaarnpaal": "Routelantaarn",
    "item.guhs.baltoslee_lantaarnpaal.lore": "Zo'n lantaarn die de sleeroute door de storm wijst. Warm licht, sneeuwmutsje erop.",
    "subtitles.guhs.baltoslee.glijden": "Sleelatten glijden over de sneeuw",
    "subtitles.guhs.baltoslee.bellen": "Sledebelletjes rinkelen",
    "subtitles.guhs.baltoslee.woef": "Guh-sledehondje: woef-njeg!",
    "subtitles.guhs.baltoslee.windvlaag": "Een windvlaag giert",
    "subtitles.guhs.baltoslee.lawine": "Een lawine rommelt",
    "subtitles.guhs.baltoslee.plof": "Plof in de sneeuw",
    "subtitles.guhs.baltoslee.ijs": "Het ijs kraakt",
    "subtitles.guhs.baltoslee.vuurkorf": "Een vuurkorf knispert",
    "subtitles.guhs.baltoslee.fanfare": "Tingeling-VAHOEG!",

    # --- the ride ---
    "gui.guhs.baltoslee.tocht.start": "Baltoguh en de guh-sledehondjes staan klaar. Door de sneeuwstorm naar de berghut, de medicijnkist halen, en dan zo snel mogelijk terug naar het ziekenhuisje. Rosy rekent op je!",
    "gui.guhs.baltoslee.sprint.start": "De Nomguh-sledesprint (%s): naar de berghut, eromheen, en terug naar de startstreep. Sneller dan Steele-Mika?",
    "gui.guhs.baltoslee.besturing": "W: hup hup, sneller! · S: remmen · A/D: sturen · Shift ingedrukt houden: stoppen. Volg de gloeiende snuffelsterretjes van Baltoguh als je niks meer ziet.",
    "gui.guhs.baltoslee.klaar.tocht": "Pootjes warm? Daar gaan we...",
    "gui.guhs.baltoslee.klaar.sprint": "Op je plaatsen... klaar...",
    "gui.guhs.baltoslee.hup": "HUP, HUP! VAHOEG!",
    "gui.guhs.baltoslee.gestopt": "Je bent gestopt. De sledehondjes brengen je terug naar de stal. Njeg, een andere keer!",
    "gui.guhs.baltoslee.weer_los": "Uitgegraven! Hup, verder!",
    "gui.guhs.baltoslee.rust.hint": "Een vuurkorf! Rem af (S) en sta even stil om de pootjes op te warmen.",
    "gui.guhs.baltoslee.rust.tocht": "Baltoguh en de sledehondjes warmen hun pootjes bij de vuurkorf. Iedereen krijgt een knuffel en een warme kaasknabbel. Njeg!",
    "gui.guhs.baltoslee.rust.sprint": "Even opwarmen bij de vuurkorf... warme pootjes zijn snelle pootjes!",
    "gui.guhs.baltoslee.rust.verder": "Warm en blij! Hup, verder!",
    "gui.guhs.baltoslee.ijsbrug": "De ijsbrug! Rustig sturen, hij is glad...",
    "gui.guhs.baltoslee.plof": "PLOF!",
    "gui.guhs.baltoslee.plof.sub": "Van de ijsbrug in de zachte sneeuw. Niks aan de hand, nog een keer!",
    "gui.guhs.baltoslee.lawine.ontweken": "Net op tijd opzij voor de lawine! VAHOEG!",
    "gui.guhs.baltoslee.lawine.boef": "BOEF!",
    "gui.guhs.baltoslee.lawine.bedolven": "Ondergesneeuwd! De sledehondjes graven je uit...",
    "gui.guhs.baltoslee.berghut": "De berghut!",
    "gui.guhs.baltoslee.berghut.sub": "Baltoguh haalt de medicijnkist...",
    "gui.guhs.baltoslee.terug": "De medicijnkist staat op de slee! Nu terug naar het ziekenhuisje, en snel: je hebt %s.",
    "gui.guhs.baltoslee.tijd.bijna": "Nog %s seconden! Hup, hup!",
    "gui.guhs.baltoslee.dieptepunt": "...",
    "gui.guhs.baltoslee.dieptepunt.sub": "De storm is te erg. Waar is Baltoguh?",
    "gui.guhs.baltoslee.helder": "De storm gaat liggen... je ziet de lichtjes van Nomguh weer!",
    "gui.guhs.baltoslee.aankomst": "Op tijd!",
    "gui.guhs.baltoslee.aankomst.sub": "Nog %s over. Het medicijn is er!",
    "gui.guhs.baltoslee.aankomst.uitleg": "Het ziekenhuisje! Baltoguh en de sledehondjes hebben het medicijn op tijd gebracht. Rosy niest nog één keer heel schattig... en lacht dan. VAHOEG!",
    "gui.guhs.baltoslee.te_laat": "Njeg...",
    "gui.guhs.baltoslee.te_laat.sub": "Net niet op tijd.",
    "gui.guhs.baltoslee.te_laat.uitleg": "Njeg, nog een keer! Rosy is gelukkig nog heel vrolijk aan het niezen, en de sledehondjes willen graag nog een rondje. Probeer het gewoon opnieuw.",
    "gui.guhs.baltoslee.sprint.keer": "Om de berghut heen! Nu terug naar de startstreep!",
    "gui.guhs.baltoslee.sprint.gewonnen": "Gewonnen!",
    "gui.guhs.baltoslee.sprint.finish": "Finish!",
    "gui.guhs.baltoslee.sprint.tijd": "Je tijd: %s",
    "gui.guhs.baltoslee.sprint.uitslag": "Sledesprint (%1$s): %2$s. Je krijgt %3$s sledebelletjes. Lawines ontweken: %4$s, ondergesneeuwd: %5$s.",
    "gui.guhs.baltoslee.sprint.record": "Nieuw eigen record: %1$s (was %2$s)! VAHOEG!",
    "gui.guhs.baltoslee.bord": "Nomguh-sledesprint",

    # --- Steele-Mika (boastful, never mean) ---
    "gui.guhs.baltoslee.steele.start": "Njeh-heh! IK ben de snelste sledeleider van heel Nomguh. Probeer me maar bij te houden!",
    "gui.guhs.baltoslee.steele.inhalen": "Doei-doei! Njeh-heh-heh!",
    "gui.guhs.baltoslee.steele.ingehaald": "Hé! Dat... dat mag niet! Wacht maar!",
    "gui.guhs.baltoslee.steele.eerst": "EERSTE! Natuurlijk. Njeh-heh! (Hij poetst zijn petje.)",
    "gui.guhs.baltoslee.steele.gewonnen": "Njeh-heh! Zei ik toch: IK ben de snelste! Maar... je deed het best aardig. Een beetje. Njeg.",
    "gui.guhs.baltoslee.steele.verloren": "Wat?! Dat was de wind! En de sneeuw! En... mijn sledehondjes hadden hun sokjes niet aan!",
    "gui.guhs.baltoslee.steele.uitgelachen": "Alle guhs van Nomguh giechelen lief. Steele-Mika wordt een beetje roze. Njeg!",
    "gui.guhs.baltoslee.steele.al_onderweg": "Je bent toch al onderweg? Njeh-heh, hup hup!",
    "gui.guhs.baltoslee.steele.geen_route": "Njeg... de route is helemaal ondergesneeuwd. Kom straks maar terug.",
    "gui.guhs.baltoslee.steele.nog_niet": "Jij? Racen tegen MIJ? Njeh-heh-heh! Eerst maar eens echt door de storm, net als die Baltoguh. Daarna praten we verder. (Mijn winkeltje is wel open, hoor.)",
    "gui.guhs.baltoslee.steele.welkom": "Zo, zo. Durf je het aan tegen de kampioen? Naar de berghut, eromheen en terug. Jouw beste tijden: makkelijk %1$s · medium %2$s · lastig %3$s.",
    "gui.guhs.baltoslee.steele.uitleg": "Luister goed, want ik zeg het maar één keer. Hup-hup (W) is sneller, remmen (S), sturen (A/D). Windvlaagjes duwen je opzij. Rommelt er een lawine? Stuur naar de ANDERE kant van de route! De ijsbrug is glad: rustig aan. En koude pootjes zijn trage pootjes: rust even bij een vuurkorf. Niet dat het helpt, want IK win toch. Njeh-heh!",
    "gui.guhs.baltoslee.optie.makkelijk": "Racen: makkelijk",
    "gui.guhs.baltoslee.optie.medium": "Racen: medium",
    "gui.guhs.baltoslee.optie.lastig": "Racen: lastig",
    "gui.guhs.baltoslee.optie.winkel": "Je winkeltje (sledebelletjes)",
    "gui.guhs.baltoslee.optie.uitleg": "Hoe werkt het?",

    # --- the panel ---
    "gui.guhs.baltoslee.hud.tocht": "De medicijntocht",
    "gui.guhs.baltoslee.hud.tocht_kist": "De medicijntocht · terug!",
    "gui.guhs.baltoslee.hud.sprint": "Sledesprint · %s",
    "gui.guhs.baltoslee.hud.tijd": "Tijd %s",
    "gui.guhs.baltoslee.hud.nog": "Nog %s",
    "gui.guhs.baltoslee.hud.heen": "Naar de berghut",
    "gui.guhs.baltoslee.hud.warmte": "Warmte",
    "gui.guhs.baltoslee.hud.vaart": "Vaart",
    "gui.guhs.baltoslee.hud.kist": "✚ medicijnkist",
    "gui.guhs.baltoslee.hud.steele": "● Steele-Mika",
    "gui.guhs.baltoslee.hud.vast": "Ondergesneeuwd! De sledehondjes graven... woef-njeg!",
    "gui.guhs.baltoslee.hud.berghut": "De berghut: Baltoguh haalt de medicijnkist... (%s)",
    "gui.guhs.baltoslee.hud.dieptepunt": "De storm is te erg... waar is Baltoguh? (%s)",
    "gui.guhs.baltoslee.hud.rust": "Warme pootjes bij de vuurkorf... (%s)",
    "gui.guhs.baltoslee.hud.lawine_rechts": "⚠ LAWINE van links! Stuur naar rechts ⇨",
    "gui.guhs.baltoslee.hud.lawine_links": "⇦ Stuur naar links! LAWINE van rechts ⚠",
    "gui.guhs.baltoslee.hud.lawine_veilig": "Goed zo, blijf daar! De lawine komt...",
    "gui.guhs.baltoslee.hud.ijsbrug": "IJsbrug: rustig sturen, niet over de rand!",
    "gui.guhs.baltoslee.hud.vlaag_links": "Windvlaag van links! ⇨",
    "gui.guhs.baltoslee.hud.vlaag_rechts": "⇦ Windvlaag van rechts!",
    "gui.guhs.baltoslee.hud.vuurkorf": "Vuurkorf! Rem af (S) om op te warmen",
    "gui.guhs.baltoslee.hud.diep": "Diepe sneeuw! Terug naar het midden",
    "gui.guhs.baltoslee.hud.koud": "Koude pootjes... rust bij een vuurkorf",
    "gui.guhs.baltoslee.hud.toetsen": "W: hup hup · S: remmen · A/D: sturen · Shift vasthouden: stoppen",

    # --- your own sneeuwslee ---
    "gui.guhs.baltoslee.eigen.uitleg": "Je eigen sneeuwslee! W: hup hup, S: remmen, A/D: sturen. De guh-sledehondjes rennen alleen over sneeuw en ijs. Sluip + rechtsklik om hem op te pakken, en geef ze eens een kaasknabbel!",
    "gui.guhs.baltoslee.eigen.geen_sneeuw": "De sledehondjes willen sneeuw onder hun pootjes, njeg!",
    "gui.guhs.baltoslee.eigen.niet_van_jou": "Dit is niet jouw slee. De sledehondjes kijken je lief maar streng aan.",
    "gui.guhs.baltoslee.eigen.knabbel": "Woef-njeg! De sledehondjes zijn heel blij met hun kaasknabbel.",
    "gui.guhs.baltoslee.eigen.geen_plek": "Daar past de slee niet. Zoek een open plekje (het liefst met sneeuw)!",
}

# advancements (tab verhalen/): name -> (title, description)
ADVANCEMENTS = {
    "balto_slee_tocht": ("Door de sneeuwstorm", "Breng met Baltoguh en de guh-sledehondjes het medicijn op tijd naar het ziekenhuisje van Nomguh"),
    "balto_slee_rustpunt": ("Warme pootjes", "Rust even met je sledehondjes bij een vuurkorf onderweg"),
    "balto_slee_ijsbrug": ("Over de ijsbrug", "Kom met de slee over een hele ijsbrug zonder eraf te ploffen"),
    "balto_slee_lawine": ("Net op tijd opzij!", "Ontwijk een lawine met je slee"),
    "balto_slee_sprint": ("De sledesprint", "Race tegen Steele-Mika naar de berghut en terug"),
    "balto_slee_steele": ("Sneller dan Steele-Mika", "Win de sledesprint van Steele-Mika (hij zegt dat het de wind was)"),
    "balto_slee_lastig": ("Kampioen van Nomguh", "Win de sledesprint op lastig. Steele-Mika wordt helemaal roze"),
    "balto_slee_winkel": ("Winterspulletjes", "Koop iets moois bij Steele-Mika voor je sledebelletjes"),
    "balto_slee_eigen": ("Hup, hup, door de sneeuw!", "Rijd 200 blokken met je eigen sneeuwslee door de sneeuw"),
}
