"""
The texts of the Guhkantoor (guhpixel slice "kantoor"): every fixed text and the POOLS the payslips, quarterly reports and
"Werknemer van de maand" certificates are put together from (Java: feature/guhpixel/kantoor/KantoorTeksten.Pool; the sizes
there are checked against this file by guhpixel_kantoor.selfcheck). Lang keys of a pool: book.guhs.guhkantoor.<pool>.<i>,
i from 0. Entries with %s get a small number that follows from the paper's seed.
Dutch only; the English is tools/lang/en/c36_px_kantoor.json.
"""

POOLS = {
    # ---------------------------------------------------------------------------------------------------- loonstrookje
    "loon.functie": [
        "Senior Vadsmanager",
        "Junior Dutjesconsulent",
        "Hoofd Knabbelzaken",
        "Stagiair Snurken",
        "Chef Toetsenbordverwarming",
        "Medewerker Binnendienst (binnen slapen)",
        "Coördinator Geeuwen",
        "Adviseur Kussenbeleid",
        "Teamleider Niksdoen",
        "Specialist Middagdutjes",
        "Directeur Vadsigheid",
        "Assistent van de Koffieautomaat",
        "Beleidsmedewerker Njeg",
        "Accountmanager Kaasknabbels",
        "Kwaliteitscontroleur Dekentjes",
        "Expert Uitrekken",
        "Projectleider Uitstellen",
        "Receptionist (slaapt bij de deur)",
        "Hoofd Dromen & Ontwikkeling",
        "Vicepresident Liggen",
    ],
    "loon.bruto": [
        "Bruto loon: 0 knabbels",
        "Bruto loon: 0 knabbels (naar boven afgerond)",
        "Bruto loon: 0 knabbels, maar wel met liefde",
        "Bruto loon: 0,0 knabbels",
        "Bruto loon: nul komma njeg",
        "Bruto loon: 0 knabbels (inclusief fooi)",
        "Bruto loon: 0 knabbels (marktconform)",
        "Bruto loon: 0 knabbels + 1 aai over de bol",
        "Bruto loon: 0 knabbels (na stevig onderhandelen)",
        "Bruto loon: 0 knabbels, alweer een record",
    ],
    "loon.inhouding": [
        "Ingehouden: %s dutjes",
        "Ingehouden: %s geeuwen",
        "Pensioenpremie: %s snurkjes",
        "Dekentjesbelasting: %s kreukels",
        "Bijdrage personeelsuitje: %s kruimels",
        "Te laat wakker geworden: %s minuten",
        "Afdracht kussenfonds: %s veertjes",
        "Kwijl op het toetsenbord: %s druppels (niet erg)",
        "Koffieautomaat: %s slokjes (niet opgedronken)",
        "Vadsverzekering: %s zuchtjes",
        "Ingehouden: %s keer omdraaien",
        "Verbruik van dromen: %s stuks",
        "Huur van het bureaustoeltje: %s wiebels",
        "Slapen onder werktijd: 0 (dat hoort zo)",
        "Kantinekosten: %s denkbeeldige knabbels",
        "Njeg-heffing: %s njegs",
        "Schoonmaak toetsenbord: %s haartjes",
        "Parkeerplek voor het staartje: %s centimeter",
        "Vakbond Vads Verenigd: %s knikjes",
        "Ingehouden: %s uitgestelde vergaderingen",
        "Slijtage van de spatiebalk: %s procent",
        "Reiskosten bureau-kussen: %s stapjes",
        "Ingehouden: %s keer \"nog vijf minuutjes\"",
        "Stroom voor het beeldscherm: %s pixels",
    ],
    "loon.toeslag": [
        "Vadstoeslag: %s extra minuten liggen",
        "Snurkbonus: %s decibel",
        "Overwerk: %s uur doorgeslapen",
        "Dertiende maand: 1 extra dutje",
        "Onregelmatig slapen: %s keer wakker geschrokken",
        "Bonus mooiste droom: %s sterretjes",
        "Thuiswerkvergoeding: %s kussens",
        "Vakantiegeld: %s dagdromen",
        "Winstdeling: %s procent van niks",
        "Gevarentoeslag: het toetsenbord was koud",
        "Prestatiebonus: %s uur niks omgegooid",
        "Ploegentoeslag: sliep in de vroege en de late dienst",
        "Aaitoeslag: %s aaitjes van collega's",
        "Zuinigheidspremie: %s keer het licht uit gelaten",
        "Jubileumbonus: %s diensten niet wakker geworden",
        "Bonus beste \"jjjjjjjj\": %s regels getypt met de wang",
    ],
    "loon.netto": [
        "Netto uit te betalen: njeg",
        "Netto: 0 knabbels en een tevreden zucht",
        "Netto: heerlijk uitgerust",
        "Netto: 8 uur slaap, belastingvrij",
        "Netto: niks, maar wel warm gelegen",
        "Netto: 1 afdruk van het toetsenbord op de wang",
        "Netto: een rond buikje vol rust",
        "Netto: 0 knabbels (wordt nooit overgemaakt)",
        "Netto: onbetaalbaar (dus ook niet betaald)",
        "Netto: vads",
        "Netto: een goed humeur",
        "Netto: precies genoeg, njeg",
    ],
    "loon.baas": [
        "Uitstekend geslapen deze dienst. Ga zo door!",
        "Vergadering uitgesteld wegens vadsen.",
        "Heeft per ongeluk 4.000 keer de letter J getypt. Prima rapport.",
        "Kwam op tijd, viel op tijd in slaap. Voorbeeldig.",
        "De printer is jaloers op zoveel rust.",
        "Graag volgende keer het kussen meenemen, njeg.",
        "Heeft de deadline gehaald door hem te verslapen.",
        "Snurkt in de maat. Goed voor de sfeer.",
        "De muis was zoek. Hij lag onder de buik.",
        "E-mail beantwoord met \"zzzzzz\". Klant tevreden.",
        "Vroeg in een droom om loonsverhoging. Is in behandeling.",
        "Functioneringsgesprek gehouden. Guh sliep. Baas ook.",
        "Het beeldscherm staat al 8 uur op de schermbeveiliging. Mooi zo.",
        "Stak collega's aan met geeuwen. Productiviteit bleef gelijk: nul.",
        "Promotie naar een zachter bureau wordt overwogen.",
        "Was één keer wakker. Ging goed. Hoeft niet nog eens.",
        "De koffie is koud geworden. Niemand vond het erg.",
        "Stond op de planning voor \"iets doen\". Planning aangepast.",
        "Weer 0 fouten gemaakt. Ook 0 dingen gedaan.",
        "Het toetsenbord is lekker warm gehouden. Bedankt, njeg.",
        "Lag op de entertoets. 312 lege regels naar de directie gestuurd.",
        "Ziekmelden hoeft niet: slapen kan gewoon op het werk.",
        "Brainstorm gehouden met het kussen. Goede ideeën, allemaal vergeten.",
        "Heeft de stilte op de afdeling uitstekend bewaakt.",
        "Vraagt of het bureau ook als bed besteld kan worden.",
        "Typt met de wang sneller dan de baas met twee poten.",
        "Heeft als enige de schermbeveiliging helemaal uitgekeken.",
        "De bureaustoel draaide nog een uur na. Onderzoek loopt.",
        "Volgende dienst graag iets zachter snurken tijdens het bellen.",
        "Vahoeg, wat een inzet! (De inzet was liggen.)",
    ],
    "loon.stempel": [
        "GOEDGEKEURD (slapend)",
        "GEZIEN, NJEG",
        "AKKOORD VAN DE DIRECTIE",
        "VADS BEVONDEN",
        "UITBETAALD IN RUST",
        "NIET WAKKER MAKEN",
        "ARCHIEF: ONDER HET KUSSEN",
        "STRENG GEHEIM (BEETJE)",
    ],
    # ------------------------------------------------------------------------------------------------- kwartaalrapport
    "kwartaal.intro": [
        "Het was weer een rustig kwartaal. Heel rustig.",
        "De directie blikt tevreden terug op drie maanden topsport in liggen.",
        "Dit kwartaal stond in het teken van rust, regelmaat en nog meer rust.",
        "Ondanks de drukte (er was geen drukte) is alles gelukt (er was niks te doen).",
        "De cijfers zijn stabiel. Opvallend stabiel. Verdacht stabiel.",
        "Ook dit kwartaal bleef het Guhkantoor trouw aan zijn kernwaarden: slapen en njeg.",
        "Na grondig onderzoek blijkt: er is niks gebeurd. Volgens plan.",
        "De aandeelhouders (twee kussens en een dekentje) zijn tevreden.",
        "Wij presenteren met trots: wederom exact hetzelfde resultaat.",
        "Een kwartaal om nooit te vergeten, al weet niemand meer wat er gebeurde.",
    ],
    "kwartaal.lijn": [
        "Productiviteit",
        "Omzet in knabbels",
        "Afgehandelde e-mails",
        "Wakkere momenten",
        "Gehaalde deadlines",
        "Groei van het bedrijf",
        "Geholpen klanten",
        "Vergaderingen die doorgingen",
    ],
    "kwartaal.staaf": [
        "Uren geslapen per dienst",
        "Dutjes per medewerker",
        "Vadsigheid per bureau",
        "Tevredenheid (van vads tot vads)",
        "Geeuwen per uur",
        "Snurkvolume per werkplek",
        "Warmte van het toetsenbord",
        "Inzet (liggend gemeten)",
    ],
    "kwartaal.taart": [
        "Tijdsbesteding: 100% vadsen",
        "Marktaandeel in dutjes: 100%",
        "Oorzaak van vertraging: 100% slaap",
        "Wat deden wij: 100% njeg",
        "Verdeling van het budget: 100% kussens",
        "Stemming op de werkvloer: 100% tevreden",
    ],
    "kwartaal.punt": [
        "Vergadering uitgesteld wegens vadsen.",
        "De jaarplanning is af: er staat \"njeg\" op.",
        "Nieuwe huisregel: fluisteren na het inklokken.",
        "De printer heeft één blaadje geprint. Het was leeg. Iedereen trots.",
        "De kantoorplant kreeg water. Verder gebeurde er weinig.",
        "De ideeënbus bevatte één idee: \"meer kussens\". Unaniem aangenomen.",
        "De koffieautomaat is tot collega benoemd.",
        "De brandoefening is doorgeslapen. Geslaagd.",
        "Er is een commissie opgericht die uitzoekt wat een commissie is.",
        "Personeelsuitje gehouden: iedereen sliep een bureau verderop.",
        "Het wachtwoord is veranderd in \"jjjjjjjj\". Niemand weet waarom.",
        "Een klant belde. Er werd teruggesnurkt. De klant belt nog eens.",
        "De telefoon ging over. Hij hield daarna vanzelf weer op.",
        "Het doel \"wakker blijven tot de lunch\" is verplaatst naar volgend jaar.",
        "De nieuwe stoelen draaien. Dat was het nieuws.",
        "Iedereen vond de schermbeveiliging \"erg mooi\".",
        "Er is één knabbel zoekgeraakt. Het spoor leidt naar een buikje.",
        "Het archief is opgeruimd: het lag onder een guh.",
        "De nieuwjaarsborrel was in maart. Eerder was niemand wakker.",
        "De notulen van de vergadering: \"zzz\". Goedgekeurd.",
        "Het internet was traag. Niemand merkte het.",
        "De deadline is gehaald, door een andere afdeling.",
        "Er kwam een bureau bij. Er wordt nu op meer plekken geslapen.",
        "Het kantoor is uitgeroepen tot stilste werkplek van de Guhmensie.",
        "De cursus \"Efficiënt geeuwen\" was een groot succes.",
        "Functie-eisen aangescherpt: moet kunnen liggen.",
        "De paperclips zijn geteld. Het zijn er nog steeds evenveel.",
        "De Prikklok tikte. Dat was het hoogtepunt van dinsdag.",
        "De toetsenborden zijn warmer dan ooit.",
        "Het personeel vroeg om een siësta. Die hadden ze al.",
        "Strategie voor komend jaar: hetzelfde, maar dan liggend.",
        "Een Mika kwam langs om te duwen. Niemand werd wakker. Hij ging maar weer.",
        "De lift is niet gebruikt. Er is ook geen lift.",
        "Het overleg over het overleg is uitgesteld tot na het overleg.",
        "De vrijdagmiddagborrel begon op maandagochtend.",
        "Er is gestemd over het raam: open. Daarna sliep iedereen frisser.",
    ],
    "kwartaal.conclusie": [
        "Conclusie: alles blijft zoals het is. Vads.",
        "Conclusie: de lijn is vlak en dat is knap.",
        "Conclusie: geen winst, geen verlies, wel uitgerust.",
        "Conclusie: wij doen niks, maar dat doen wij heel goed.",
        "Conclusie: njeg.",
        "Conclusie: de cijfers liegen niet. Ze slapen.",
        "Conclusie: stabiliteit is ook een resultaat.",
        "Conclusie: het gaat uitstekend, vermoeden wij.",
        "Conclusie: nul is ook een getal, en nog een rond getal ook.",
        "Conclusie: het plan werkte, want er was geen plan.",
        "Conclusie: iedereen is tevreden en niemand weet waarover.",
        "Conclusie: beter dan dit wordt het niet. Slechter ook niet.",
    ],
    "kwartaal.vooruit": [
        "Vooruitblik: volgend kwartaal hetzelfde, maar zachter.",
        "Vooruitblik: de vergadering wordt opnieuw uitgesteld.",
        "Vooruitblik: meer kussens, minder wekkers.",
        "Vooruitblik: wij mikken op een nog vlakkere lijn.",
        "Vooruitblik: de directie gaat eerst even liggen.",
        "Vooruitblik: misschien iets doen. Waarschijnlijk niet.",
        "Vooruitblik: een groei van 0 procent, ruim binnen bereik.",
        "Vooruitblik: een tweede kantoorplant wordt overwogen.",
        "Vooruitblik: nieuwe doelen volgen zodra iemand wakker is.",
        "Vooruitblik: het wordt weer lekker stil.",
        "Vooruitblik: wij blijven doen waar wij goed in zijn. Njeg.",
        "Vooruitblik: de toekomst is rond, roze en slaperig.",
    ],
    # -------------------------------------------------------------------------------------------------------- oorkonde
    "oorkonde.reden": [
        "Omdat niemand zo overtuigend op een toetsenbord kan liggen.",
        "Wegens het langste dutje dat de Prikklok ooit heeft gemeten.",
        "Voor het onvermoeibaar moe zijn.",
        "Omdat het snurken klonk als een tevreden printer.",
        "Voor uitzonderlijke inzet in het niks doen.",
        "Wegens het warmhouden van de hele afdeling.",
        "Omdat de wekker het heeft opgegeven.",
        "Voor het doorslapen van drie vergaderingen op rij.",
        "Wegens de mooiste afdruk van de spatiebalk op een wang.",
        "Omdat zelfs de schermbeveiliging er rustig van werd.",
        "Voor het nooit, maar dan ook nooit, te vroeg wakker worden.",
        "Wegens vadsigheid van het allerhoogste niveau.",
    ],
    "oorkonde.handtekening": [
        "De directie (pootafdruk)",
        "Getekend: de baas (sliep tijdens het tekenen)",
        "Namens het hele kantoor: njeg",
        "De Prikklok (tik)",
        "Goedgekeurd door de koffieautomaat",
        "De ondernemingsraad (twee kussens)",
    ],
    "maand": [
        "januari", "februari", "maart", "april", "mei", "juni", "juli", "augustus", "september", "oktober", "november", "december",
    ],
}

B = "book.guhs.guhkantoor."
G = "gui.guhs.guhkantoor."

TEXTS = {
    # --- blocks and items ---
    "block.guhs.guhkantoor_prikklok": "Prikklok",
    "block.guhs.guhkantoor_prikklok.lore": "Het hart van je Guhkantoor. Rechtsklik: zet je guhs aan het werk (lees: laat ze lekker slapen).",
    "block.guhs.guhkantoor_bureautje": "Bureautje",
    "block.guhs.guhkantoor_bureautje.lore": "Bureau, oude computer en krukje. Zet het binnen 8 blokken van een Prikklok: er passen er 4 op één klok.",
    "block.guhs.guhkantoor_loonstrookje": "Loonstrookje",
    "block.guhs.guhkantoor_loonstrookje.lore": "Rechtsklik in de lucht: lezen. Op een muur: ophangen.",
    "block.guhs.guhkantoor_kwartaalrapport": "Kwartaalrapport",
    "block.guhs.guhkantoor_kwartaalrapport.lore": "Rechtsklik in de lucht: lezen. Op een muur: ophangen.",
    "block.guhs.guhkantoor_oorkonde": "Oorkonde Werknemer van de maand",
    "block.guhs.guhkantoor_oorkonde.lore": "Rechtsklik in de lucht: lezen. Op een muur: ophangen.",
    G + "papier.van": "Van: %s",
    G + "papier.nr": "Nr. %s",
    G + "papier.kantoor": "Guhkantoor van %s",
    G + "papier.leeg": "Blanco formulier. Echte krijg je van je guhs op de Prikklok.",
    # --- the papers: fixed lines ---
    B + "bedrijf": "Guhkantoor B.V. (Besloten Vadsschap)",
    B + "loon.titel": "LOONSTROOKJE",
    B + "loon.nr": "Nr. %s",
    B + "loon.werknemer": "Werknemer: %s",
    B + "loon.functie": "Functie: %s",
    B + "loon.datum": "Datum: %s",
    B + "loon.dienst": "Dienst: 8 uur, waarvan geslapen: 8 uur",
    B + "loon.opmerking": "Opmerking van de baas:",
    B + "kwartaal.titel": "KWARTAALRAPPORT",
    B + "kwartaal.periode": "Kwartaal %1$s van boekjaar %2$s",
    B + "kwartaal.van": "Guhkantoor van %s",
    B + "kwartaal.hoogtepunten": "Hoogtepunten",
    B + "kwartaal.topper": "Werknemer van de maand: %s",
    B + "kwartaal.as.veel": "veel",
    B + "kwartaal.as.niks": "niks",
    B + "kwartaal.as.tijd": "tijd",
    B + "kwartaal.niemand": "niemand (iedereen sliep thuis)",
    B + "oorkonde.titel": "WERKNEMER VAN DE MAAND",
    B + "oorkonde.maand": "%1$s %2$s",
    B + "oorkonde.voor": "Met trots uitgereikt aan",
    B + "oorkonde.uren": "Sliep deze maand %s uur onder werktijd.",
    # --- the Prikklok screen ---
    G + "scherm.titel": "Prikklok",
    G + "scherm.grap.1": "Werktijd: 8 echte uren. Pauze: ook 8 uur.",
    G + "scherm.grap.2": "Hier wordt hard gewerkt. Nou ja. Hier wordt gelegen.",
    G + "scherm.grap.3": "Stil zijn, njeg: de collega's slapen.",
    G + "scherm.bureau": "Bureau %s",
    G + "scherm.leeg": "Leeg. Het toetsenbord is nog koud.",
    G + "scherm.geen_bureau": "Hier kan nog een Bureautje bij (binnen 8 blokken).",
    G + "scherm.van": "%1$s (van %2$s)",
    G + "scherm.slaapt": "Slaapt al %1$s. Loonstrookje over %2$s.",
    G + "scherm.klaar": "Er liggen %s loonstrookjes klaar!",
    G + "scherm.klaar.1": "Er ligt een loonstrookje klaar!",
    G + "scherm.tijd": "%1$s u %2$s min",
    G + "scherm.knop.werk": "Aan het werk",
    G + "scherm.knop.huis": "Naar huis",
    G + "scherm.knop.loon": "Loon (%s)",
    G + "scherm.knop.inklokken": "Inklokken",
    G + "scherm.knop.terug": "Terug",
    G + "scherm.kies": "Wie gaat er vandaag heel hard slapen?",
    G + "scherm.maand": "Werknemer van de maand: %1$s (%2$s uur geslapen)",
    G + "scherm.maand.geen": "Werknemer van de maand: nog niemand, njeg",
    G + "scherm.tip.huis": "Uitklokken: je guh komt weer naast het bureau staan. Loonstrookjes die klaarliggen krijg je mee.",
    G + "scherm.tip.loon": "Na elke 8 echte uren slapen ligt er een loonstrookje. Er passen er 3 in het postvakje.",
    G + "scherm.tip.ander": "Deze guh werkt voor iemand anders. Laat maar lekker liggen.",
    G + "kiezer.ver": "Te ver weg: breng hem naar het kantoor",
    G + "kiezer.werkt": "Ligt al op een toetsenbord",
    G + "kiezer.vakantie": "Is op vakantie",
    G + "kiezer.weg": "Is er nu even niet",
    # --- messages ---
    G + "meld.ingeklokt": "%s klokt in en valt meteen in slaap op het toetsenbord.",
    G + "meld.uitgeklokt": "%s klokt uit en rekt zich uit. Wat een dag!",
    G + "meld.loon": "%1$s loonstrookje(s) van %2$s. Bruto: 0 knabbels, njeg.",
    G + "meld.rapport": "Er zit ook een kwartaalrapport bij. De lijn is vlak!",
    G + "meld.oorkonde": "%s is Werknemer van de maand! De oorkonde zit in je zak.",
    G + "meld.te_ver": "Die guh is te ver weg. Breng hem eerst naar het kantoor, njeg.",
    G + "meld.niet_jouw": "Deze guh werkt voor iemand anders, njeg.",
    G + "meld.bezet": "Aan dit bureau slaapt al iemand.",
    G + "meld.geen_klok": "Dit Bureautje hoort nog bij geen Prikklok. Zet er een binnen 8 blokken, njeg.",
    G + "meld.vol": "Deze Prikklok heeft al 4 Bureautjes. Meer past er niet op de klok.",
    G + "meld.gekoppeld": "Bureautje aangesloten op de Prikklok (%s van 4).",
    G + "meld.geen_bureaus": "De Prikklok staat. Zet er nu Bureautjes omheen (binnen 8 blokken).",
    G + "meld.nog_niks": "Nog geen loonstrookje: een dienst duurt 8 echte uren.",
    G + "meld.postvak": "Er lag nog post van het Guhkantoor voor je klaar.",
    G + "meld.terug": "%s is terug van het Guhkantoor.",
    G + "meld.weg": "Het bureau is weg, dus %s heeft vrij.",
    G + "meld.mislukt": "Dat lukte even niet. Probeer het nog eens, njeg.",
    # --- Guhdex ---
    G + "gids.kop": "Guhkantoor",
    G + "gids.uitleg": "Zet je guhs aan het werk bij de Prikklok. Ze slapen op het toetsenbord en na 8 echte uren krijg je een loonstrookje. "
                       "Levert niks op. Dat is het mooie.",
    G + "gids.werkt": "Nu aan het werk",
    G + "gids.loon": "Loonstrookjes",
    G + "gids.rapport": "Kwartaalrapporten",
    G + "gids.oorkonde": "Oorkondes",
    G + "gids.maand": "Werknemer van de maand",
    G + "gids.maand.waarde": "%1$s (%2$s uur)",
    G + "gids.maand.geen": "nog niemand",
    # --- shop ---
    G + "winkel.set.naam": "Guhkantoor-set",
    G + "winkel.set": "Een Prikklok en één Bureautje. Je guhs slapen er op het toetsenbord en krijgen er een loonstrookje voor. "
                      "Alleen voor de sier, echt waar, njeg.",
    G + "winkel.bureautje": "Nog een werkplek. Er passen 4 Bureautjes op één Prikklok.",
    G + "winkel.eis": "Koop eerst de Guhkantoor-set, njeg.",
    # --- sounds ---
    "subtitles.guhs.guhkantoor.inklokken": "Prikklok stempelt",
    "subtitles.guhs.guhkantoor.uitklokken": "Guh klokt uit",
    "subtitles.guhs.guhkantoor.printer": "Printer ratelt",
    "subtitles.guhs.guhkantoor.toetsenbord": "Guh rolt over het toetsenbord",
}


def alle():
    """Every text of the slice: the fixed ones and the pools."""
    out = dict(TEXTS)
    for pool, regels in POOLS.items():
        for i, nl in enumerate(regels):
            out[f"{B}{pool}.{i}"] = nl
    return out
