"""
The Dutch texts of the guhpixel slice "grap2" (the Guhmon-gevecht and Boer zoekt Guh). Dutch is the source; the English
is in tools/lang/en/c33_px_grap2.json and follows tools/lang/GLOSSARY.md + tools/lang/glossary_px/grap2.md.
TEXTS: lang key -> Dutch. AFTITELING: how many (job, name) pairs the credits of Boer zoekt Guh have (Java: Bzg.AFTITELING_REGELS
is twice that).
"""

TEXTS = {
    "entity.guhs.guh_npc.guhmon_gymleider": "Gymleider Dutjes",
    "entity.guhs.guh_npc.bzg_presentatrice": "Presentatrice Guhvon",
    "entity.guhs.guh_npc.bzg_boer": "Boer Guhrrit",
    "entity.guhs.guhmon_guh": "Guhmon",
    "entity.guhs.bzg_guh": "Kandidaat-guh",
    "block.guhs.guhmon_badgedoos": "Badgedoosje",
    "block.guhs.guhmon_badgedoos.lore": "Plek voor acht gymbadges. Klik erop met een badge. De andere vijf gyms zijn dicht wegens dutje.",
    "item.guhs.guhmon_badge_dutjes": "Dutjesbadge",
    "item.guhs.guhmon_badge_dutjes.lore": "Van Gymleider Dutjes, omdat jouw guh als eerste sliep.",
    "item.guhs.guhmon_badge_njeg": "Njegbadge",
    "item.guhs.guhmon_badge_njeg.lore": "Voor wie een Dutje liet mislukken met een goed getimede Njeg.",
    "item.guhs.guhmon_badge_knabbel": "Knabbelbadge",
    "item.guhs.guhmon_badge_knabbel.lore": "Voor wie in slaap viel met een vol buikje.",
    "item.guhs.guhmon_trainerspet": "Guhmon-trainerspet",
    "block.guhs.bzg_brievenbus": "Brievenbus",
    "block.guhs.bzg_brievenbus.lore": "Uit de studio van Boer zoekt Guh. Thuis zit er nooit post in, njeg.",
    "block.guhs.bzg_ingelijste_brief": "Ingelijste brief",
    "block.guhs.bzg_ingelijste_brief.lore": "Het bedankbriefje van Boer Guhrrit. Klik om te lezen.",
    "item.guhs.bzg_strohoed": "Strohoed van Boer Guhrrit",
    "item.guhs.bzg_overall": "Overall van Boer Guhrrit",
    "gui.guhs.kledingbron.guhmon_gym": "Guhpixel: de gym van Gymleider Dutjes",
    "gui.guhs.kledingbron.bzg_show": "Guhpixel: Boer zoekt Guh",
    "subtitles.guhs.guhmon.gevecht": "Een Guhmon-gevecht begint",
    "subtitles.guhs.guhmon.zet": "Een guh doet iets slaperigs",
    "subtitles.guhs.guhmon.slaapt": "Een guh valt in slaap",
    "subtitles.guhs.guhmon.gewonnen": "Gewonnen door te slapen",
    "subtitles.guhs.bzg.tune": "De tune van Boer zoekt Guh",
    "subtitles.guhs.bzg.brief": "Een brief ritselt",
    "gui.guhs.guhmon.grap.naam": "Guhmon-gevecht",
    "gui.guhs.guhmon.grap.uitleg": "Daag Gymleider Dutjes uit met een van je eigen guhs. Geen HP maar een SLAAPbalk: wie het eerst slaapt, wint.",
    "gui.guhs.guhmon.grap.stap.1": "Loop de gym in en daag Gymleider Dutjes uit",
    "gui.guhs.guhmon.grap.stap.2": "Kies je Guhmon (of leen er eentje)",
    "gui.guhs.guhmon.grap.stap.3": "Val in slaap voordat de tegenstander het doet",
    "gui.guhs.guhmon.grap.stap.4": "Neem je Dutjesbadge in ontvangst",
    "gui.guhs.guhmon.grap.clou": "DE SLAPER WINT!",
    "quest.guhs.guhmon.lobby.hallo": "Gaap... O, een uitdager! Ik ben Gymleider Dutjes. In mijn gym vechten guhs niet met klappen, maar met dutjes. Wie het eerst slaapt, wint. Durf je, njeg?",
    "quest.guhs.guhmon.lobby.weer": "Daar is de kampioen weer! Mijn Snurkel heeft sindsdien extra geoefend. Hij sliep gisteren negentien uur. Nog een potje?",
    "quest.guhs.guhmon.lobby.uitleg": "Je kiest een van je tamme guhs. In de gym verschijnt een kopie, de echte blijft lekker thuis. Geen guh? Dan krijg je een leenguh. Vier zetten: Vadsen, Njeg, Knabbel eten en Dutje. Niets doet pijn. Verliezen kost niets: gewoon nog een keer.",
    "quest.guhs.guhmon.optie.uitdagen": "Ik daag je uit!",
    "quest.guhs.guhmon.optie.opnieuw": "Nog een gevecht!",
    "quest.guhs.guhmon.optie.uitleg": "Hoe werkt een Guhmon-gevecht?",
    "quest.guhs.guhmon.optie.kwijt": "Mijn badges zijn kwijt, njeg",
    "quest.guhs.guhmon.kwijt.hier": "Gymleider Dutjes had nog een reservedoosje onder zijn kussen liggen.",
    "quest.guhs.guhmon.kwijt.niets": "Je hebt alles nog bij je, njeg. Kijk maar in je zakken.",
    "quest.guhs.guhmon.gym.welkom": "Welkom in de Dutjesgym! Sst, het publiek slaapt al. Stap op de mat of tik me aan als je er klaar voor bent.",
    "quest.guhs.guhmon.gym.gewonnen": "Ongelooflijk... %s sliep eerder dan mijn Snurkel! Dat is nog nooit iemand gelukt. Vandaag dan. Hier, de Dutjesbadge is van jou!",
    "gui.guhs.guhmon.gym.klik": "KLIK OM UIT TE DAGEN",
    "gui.guhs.guhmon.tegen.naam": "Snurkel",
    "gui.guhs.guhmon.leenguh.naam": "Leenguh",
    "gui.guhs.guhmon.kies.niet_van_jou": "Die guh ken ik niet, njeg. Kies er een van jezelf.",
    "gui.guhs.guhmon.publiek.slaapt": "Sst! Het publiek slaapt. Dat hoort zo.",
    "gui.guhs.guhmon.publiek.wakker": "Snurkel kijkt je slaperig aan.",
    "gui.guhs.guhmon.badgedoos.zit_er_al": "Die badge zit er al in, njeg.",
    "gui.guhs.guhmon.badgedoos.stand": "%s van de 8 badges. De andere gyms zijn dicht wegens dutje.",
    "gui.guhs.guhmon.gids.stand": "Gewonnen / verloren",
    "gui.guhs.guhmon.gids.stand.waarde": "%s / %s",
    "gui.guhs.guhmon.gids.badges": "Gymbadges",
    "gui.guhs.guhmon.gids.badge.dutjes": "Win het gevecht van Gymleider Dutjes.",
    "gui.guhs.guhmon.gids.badge.njeg": "Win een gevecht waarin jouw Njeg een Dutje van Snurkel liet mislukken.",
    "gui.guhs.guhmon.gids.badge.knabbel": "Val in slaap terwijl je buikje nog vol zit van Knabbel eten.",
    "gui.guhs.guhmon.kies.titel": "Kies je Guhmon",
    "gui.guhs.guhmon.kies.knop": "Ik kies jou!",
    "gui.guhs.guhmon.kies.uitleg": "Er verschijnt een kopie in de gym: je echte guh blijft lekker thuis. Onderaan staat de leenguh van de gym.",
    "gui.guhs.guhmon.kies.geen_eigen": "Je hebt nog geen tamme guhs. Geeft niks: de gym leent je er eentje. Hij heet Leenguh.",
    "gui.guhs.guhmon.gevecht.titel": "Guhmon-gevecht",
    "gui.guhs.guhmon.zet.vadsen": "Vadsen",
    "gui.guhs.guhmon.zet.vadsen.tip": "+25 slaap voor je eigen guh. Lekker liggen.",
    "gui.guhs.guhmon.zet.njeg": "Njeg",
    "gui.guhs.guhmon.zet.njeg.tip": "-15 slaap bij de tegenstander. Niet erg effectief, maar zijn volgende Dutje mislukt.",
    "gui.guhs.guhmon.zet.knabbel": "Knabbel eten",
    "gui.guhs.guhmon.zet.knabbel.tip": "+10 slaap nu, en nog twee beurten +10 door een vol buikje.",
    "gui.guhs.guhmon.zet.dutje": "Dutje",
    "gui.guhs.guhmon.zet.dutje.tip": "+40 slaap! Mislukt als de tegenstander net Njeg zei.",
    "gui.guhs.guhmon.knop.verder": "Badge ophalen",
    "gui.guhs.guhmon.knop.opnieuw": "Nog een keer!",
    "gui.guhs.guhmon.scherm.dicht": "Het gevecht wacht op je. Tik Gymleider Dutjes aan om verder te gaan.",
    "gui.guhs.guhmon.tekst.intro.1": "Gymleider Dutjes wil vechten! Nou ja, vechten...",
    "gui.guhs.guhmon.tekst.intro.2": "Gymleider Dutjes stuurt %s! Die is al een beetje slaperig...",
    "gui.guhs.guhmon.tekst.intro.3": "Hup, %s! Wie het eerst slaapt, wint.",
    "gui.guhs.guhmon.tekst.vadsen": "%s gebruikt Vadsen! Het is super vadsig!",
    "gui.guhs.guhmon.tekst.njeg": "%s gebruikt Njeg! Het is niet erg effectief... %s schrikt een beetje wakker.",
    "gui.guhs.guhmon.tekst.knabbel": "%s gebruikt Knabbel eten! Het buikje zit vol.",
    "gui.guhs.guhmon.tekst.knabbel_vol": "%s eet nog een knabbel! Het buikje zat al vol, maar er past altijd nog eentje bij.",
    "gui.guhs.guhmon.tekst.dutje": "%s gebruikt Dutje! Zzz... Het is heel erg effectief!",
    "gui.guhs.guhmon.tekst.dutje_mislukt": "%s gebruikt Dutje... maar die Njeg galmt nog na! Het mislukt.",
    "gui.guhs.guhmon.tekst.buikje": "%s wordt slaperig van het volle buikje.",
    "gui.guhs.guhmon.tekst.slaapt": "%s is in slaap gevallen!",
    "gui.guhs.guhmon.tekst.gewonnen": "%s sliep als eerste. Jij wint het gevecht!",
    "gui.guhs.guhmon.tekst.verloren": "%s sliep als eerste. Gymleider Dutjes wint... Maar %s mag gewoon nog een keer.",
    "gui.guhs.guhmon.tekst.wat_nu": "Wat moet %s doen?",
    "gui.guhs.guhmon.tekst.na_winst": "Je guh snurkt tevreden. Gymleider Dutjes zoekt de badge onder zijn kussen.",
    "gui.guhs.guhmon.tekst.na_verlies": "Geeft niks, njeg! Verliezen kost niets. Schud je guh wakker en probeer het nog eens.",
    "gui.guhs.guhmon.tekst.let_op": "Let op: de Njeg galmt nog na. Een Dutje mislukt nu.",
    "gui.guhs.guhmon.ballon.vadsen": "~vads~",
    "gui.guhs.guhmon.ballon.njeg": "NJEG!",
    "gui.guhs.guhmon.ballon.knabbel": "Nom nom",
    "gui.guhs.guhmon.ballon.knabbel_vol": "Nom nom nom",
    "gui.guhs.guhmon.ballon.dutje": "Zzz...",
    "gui.guhs.guhmon.ballon.dutje_mislukt": "Huh!?",
    "gui.guhs.guhmon.ballon.buikje": "Oef, vol",
    "gui.guhs.guhmon.balk.slaap": "SLAAP",
    "gui.guhs.guhmon.balk.maag": "vol buikje: nog %s",
    "gui.guhs.bzg.grap.naam": "Boer zoekt Guh",
    "gui.guhs.bzg.grap.uitleg": "Het tv-programma van Presentatrice Guhvon. Boer Guhrrit zoekt een guh om samen mee te dutten. Jij helpt een handje.",
    "gui.guhs.bzg.grap.stap.1": "Praat met Presentatrice Guhvon: de uitzending begint",
    "gui.guhs.bzg.grap.stap.2": "Haal de drie brieven uit de brievenbus en lees ze",
    "gui.guhs.bzg.grap.stap.3": "De logeerweek: stop iedereen op de boerderij lekker in",
    "gui.guhs.bzg.grap.stap.4": "De keuze: help Boer Guhrrit kiezen",
    "gui.guhs.bzg.grap.stap.5": "Kijk de aftiteling",
    "gui.guhs.bzg.grap.clou": "ZE BLIJVEN ALLEMAAL!",
    "quest.guhs.bzg.lobby.hallo": "Hallo kijkbuisguhtjes! Ik ben Guhvon, en dit is Boer zoekt Guh. Boer Guhrrit zoekt iemand om samen mee te dutten in het hooi. Er zijn drie brieven binnen. Help je mee met de opnames?",
    "quest.guhs.bzg.lobby.weer": "Daar ben je weer! De herhaling van jouw aflevering was een kijkcijferkanon. Vooral het stuk waarin niemand iets deed. Nog een keer opnemen?",
    "quest.guhs.bzg.lobby.uitleg": "Je leest de brieven, je helpt tijdens de logeerweek en je staat Boer Guhrrit bij als hij moet kiezen. Het is maar televisie, njeg: na de aftiteling is het klaar.",
    "quest.guhs.bzg.optie.meedoen": "Ik doe mee!",
    "quest.guhs.bzg.optie.opnieuw": "Nog een aflevering!",
    "quest.guhs.bzg.optie.uitleg": "Wat moet ik doen?",
    "quest.guhs.bzg.optie.kwijt": "Mijn ingelijste brief is kwijt, njeg",
    "quest.guhs.bzg.kwijt.hier": "Guhvon had nog een kopietje van de brief in haar tas.",
    "quest.guhs.bzg.kwijt.niets": "Je hebt alles nog bij je, njeg. Kijk maar in je zakken.",
    "quest.guhs.bzg.boer.los": "Ik hoor eigenlijk op de boerderij. Daar is het hooi zachter.",
    "quest.guhs.bzg.boer.vroeg": "Sst, de camera's draaien nog niet. Ik oefen vast mijn verraste gezicht.",
    "quest.guhs.bzg.boer.wakker": "Gaap... Wat een week! Ik heb niets meegekregen, maar het was heerlijk. En nu moet ik kiezen? Help me even, njeg.",
    "quest.guhs.bzg.studio.welkom": "En... actie! Welkom in de studio. Kom maar even bij me staan, dan beginnen we.",
    "quest.guhs.bzg.studio.brieven": "De brievenbus staat daar, bij de bank. Alle drie de brieven lezen, hoor!",
    "quest.guhs.bzg.studio.logeren": "De logeerweek is begonnen! Loop door het decor naar de boerderij. Iedereen slaapt al. Stop ze maar lekker in.",
    "quest.guhs.bzg.studio.keuze": "Spannend! Boer Guhrrit moet kiezen. Ga hem maar helpen.",
    "quest.guhs.bzg.studio.samen": "Sst. Ze slapen. Dit is de mooiste televisie die ik ooit gemaakt heb.",
    "quest.guhs.bzg.intro.1": "Lieve kijkers, welkom bij een gloednieuw seizoen van Boer zoekt Guh!",
    "quest.guhs.bzg.intro.2": "Dit jaar: Boer Guhrrit. Hij heeft een boerderij, een strohoed en heel veel hooi. Het enige wat hij mist, is iemand om naast te snurken.",
    "quest.guhs.bzg.intro.3": "We kregen stapels brieven! Nou ja, drie. De kandidaten zitten al op de bank. Zwaai maar even.",
    "quest.guhs.bzg.intro.4": "Wil jij de brieven uit de brievenbus halen en ze voorlezen? Ik ben mijn leesbril kwijt, njeg.",
    "quest.guhs.bzg.kandidaat.hoi.1": "Hoi! Ik ben helemaal uit de stad gekomen. In de trein heb ik alvast een dutje gedaan.",
    "quest.guhs.bzg.kandidaat.hoi.2": "Dag... Is dat echt hooi daar? Ik droom er al weken van.",
    "quest.guhs.bzg.kandidaat.hoi.3": "Goedendag. Ik snurk in drie toonsoorten. Dat staat ook in mijn brief.",
    "quest.guhs.bzg.keuze.vraag": "Tukkie, Dommelien of Snurkbert... Ze sliepen alle drie zo mooi. Wie moet ik kiezen, njeg?",
    "quest.guhs.bzg.keuze.optie.1": "Tukkie!",
    "quest.guhs.bzg.keuze.optie.2": "Dommelien!",
    "quest.guhs.bzg.keuze.optie.3": "Snurkbert!",
    "quest.guhs.bzg.keuze.optie.4": "Gewoon allemaal?",
    "quest.guhs.bzg.samen.twijfel": "%s? Ja... Maar de andere twee dan? Die liggen er ook zo lief bij. Ik kan het niet, njeg. Ik kan niet kiezen!",
    "quest.guhs.bzg.samen.allemaal": "Allemaal? Mag dat? Dat staat vast niet in het draaiboek... Maar ik kon toch al niet kiezen, njeg!",
    "quest.guhs.bzg.samen.2": "Weet je wat? Het hooi is groot genoeg. Jullie blijven gewoon alle drie. Als vrienden. Slaapvrienden.",
    "quest.guhs.bzg.samen.3": "VAHOEG! Mag ik dan het plekje bij het raam?",
    "quest.guhs.bzg.samen.4": "Lieve kijkers, dit hebben we nog nooit meegemaakt: iedereen wint en iedereen slaapt. Tot volgend seizoen!",
    "gui.guhs.bzg.kandidaat.1": "Tukkie",
    "gui.guhs.bzg.kandidaat.2": "Dommelien",
    "gui.guhs.bzg.kandidaat.3": "Snurkbert",
    "gui.guhs.bzg.studio.klik": "KLIK: DE UITZENDING BEGINT",
    "gui.guhs.bzg.brievenbus.leeg.1": "Geen post vandaag, njeg.",
    "gui.guhs.bzg.brievenbus.leeg.2": "Alleen een foldertje van het Reisbureau.",
    "gui.guhs.bzg.brievenbus.leeg.3": "Er ligt een kruimel in. Meer niet.",
    "gui.guhs.bzg.brievenbus.leeg.4": "Leeg. De postguh slaapt nog.",
    "gui.guhs.bzg.brievenbus.eerst": "Praat eerst even met Presentatrice Guhvon.",
    "gui.guhs.bzg.brieven.nog": "%s van de %s brieven gelezen. Lees ze alle drie, njeg.",
    "gui.guhs.bzg.logeerweek.titel": "DE LOGEERWEEK",
    "gui.guhs.bzg.logeerweek.onder": "Iedereen slaapt al. Stop ze lekker in.",
    "gui.guhs.bzg.keuze.titel": "DE KEUZE",
    "gui.guhs.bzg.keuze.onder": "Boer Guhrrit is wakker. Ga met hem praten.",
    "gui.guhs.bzg.slaapt": "%s slaapt. Sst.",
    "gui.guhs.bzg.al_ingestopt": "%s ligt er al warmpjes bij.",
    "gui.guhs.bzg.ingestopt": "Dag %s van de logeerweek: %s is lekker ingestopt.",
    "gui.guhs.bzg.gids.ingestopt": "Slapers ingestopt",
    "gui.guhs.bzg.brief.titel": "Brieven voor Boer Guhrrit",
    "gui.guhs.bzg.brief.knop": "Brief %s",
    "gui.guhs.bzg.brief.volgende": "Volgende brief",
    "gui.guhs.bzg.brief.teller": "brief %s van %s",
    "book.guhs.bzg.brief.1.aanhef": "Lieve Boer Guhrrit,",
    "book.guhs.bzg.brief.1.tekst": "Ik ben Tukkie en ik woon in de stad. Daar is het druk en lawaaiig, dus ik slaap pas om negen uur 's ochtends uit. Mijn hobby's zijn middagdutjes, ochtenddutjes en wandelen (naar mijn mandje). Ik heb gehoord dat het op het platteland zo stil is dat je je eigen gegaap kunt horen. Dat lijkt me heerlijk. Ik kan trouwens ook staand slapen, handig bij het melken.",
    "book.guhs.bzg.brief.1.groet": "Slaperige groetjes, Tukkie",
    "book.guhs.bzg.brief.2.aanhef": "Beste Boer Guhrrit,",
    "book.guhs.bzg.brief.2.tekst": "Mijn naam is Dommelien. Al sinds ik een klein guhtje was, droom ik ervan om in echt hooi te liggen. Thuis heb ik alleen een kussen, en dat is toch anders. Ik ben heel zorgzaam: als jij slaapt, slaap ik gezellig mee. Ik houd van lange gesprekken, zolang ze niet te lang duren. Koken kan ik niet, maar ik kan wel heel lief naar kaasknabbels kijken tot iemand ze aan mij geeft.",
    "book.guhs.bzg.brief.2.groet": "Veel liefs en welterusten, Dommelien",
    "book.guhs.bzg.brief.3.aanhef": "Geachte Boer Guhrrit,",
    "book.guhs.bzg.brief.3.tekst": "Hierbij solliciteer ik, Snurkbert, naar de functie van uw guh. Ik heb elf jaar ervaring met slapen en snurk in drie toonsoorten. Referenties zijn op aanvraag beschikbaar, maar die slapen nu. Mijn sterke punten: liggen, zitten en liggen. Mijn zwakke punt: opstaan. Ik ben per direct beschikbaar, tenzij ik net slaap. Ik hoor graag van u, het liefst na het middagdutje.",
    "book.guhs.bzg.brief.3.groet": "Hoogachtend, Snurkbert",
    "book.guhs.bzg.bedankbrief.aanhef": "Lieve %s,",
    "book.guhs.bzg.bedankbrief.tekst": "Bedankt voor je hulp bij de uitzending. Tukkie, Dommelien en Snurkbert wonen nu alle drie op de boerderij. We staan elke dag vroeg op, om een uur of elf, en dan gaan we meteen even liggen. De koeien melken zichzelf zo'n beetje. Het hooi is nog nooit zo plat geweest. Kom gerust eens langs, maar klop zachtjes: er slaapt altijd wel iemand. Je hebt ons toen zo mooi ingestopt, njeg.",
    "book.guhs.bzg.bedankbrief.groet": "Dikke knuffel van Boer Guhrrit (en de rest, die slaapt)",
    "gui.guhs.bzg.aftiteling.titel": "BOER ZOEKT GUH",
    "gui.guhs.bzg.aftiteling.onder": "een programma van Guhpixel TV",
    "gui.guhs.bzg.aftiteling.rol.1": "Presentatie",
    "gui.guhs.bzg.aftiteling.naam.1": "Guhvon",
    "gui.guhs.bzg.aftiteling.rol.2": "De boer",
    "gui.guhs.bzg.aftiteling.naam.2": "Boer Guhrrit (sliep tijdens de opnames)",
    "gui.guhs.bzg.aftiteling.rol.3": "De kandidaten",
    "gui.guhs.bzg.aftiteling.naam.3": "Tukkie, Dommelien en Snurkbert",
    "gui.guhs.bzg.aftiteling.rol.4": "Instoppen",
    "gui.guhs.bzg.aftiteling.naam.4": "jij",
    "gui.guhs.bzg.aftiteling.rol.5": "Camera",
    "gui.guhs.bzg.aftiteling.naam.5": "een guh die er per ongeluk tegenaan leunde",
    "gui.guhs.bzg.aftiteling.rol.6": "Geluid",
    "gui.guhs.bzg.aftiteling.naam.6": "snurken, live opgenomen",
    "gui.guhs.bzg.aftiteling.rol.7": "Hooi",
    "gui.guhs.bzg.aftiteling.naam.7": "het hooi",
    "gui.guhs.bzg.aftiteling.rol.8": "Catering",
    "gui.guhs.bzg.aftiteling.naam.8": "kaasknabbels (op voor de eerste opname)",
    "gui.guhs.bzg.aftiteling.rol.9": "Regie",
    "gui.guhs.bzg.aftiteling.naam.9": "niemand, het ging vanzelf",
    "gui.guhs.bzg.aftiteling.rol.10": "Met dank aan",
    "gui.guhs.bzg.aftiteling.naam.10": "alle guhs die wakker bleven tot de aftiteling",
    "gui.guhs.bzg.aftiteling.rol.11": "Tijdens dit programma",
    "gui.guhs.bzg.aftiteling.naam.11": "is geen enkel dutje onderbroken",
    "gui.guhs.bzg.aftiteling.einde": "EINDE",
    "gui.guhs.bzg.aftiteling.einde.onder": "(ze slapen nog steeds)",
    "gui.guhs.bzg.aftiteling.sluit": "klik of spatie: overslaan",
}

AFTITELING = 11
