"""
Opa Guh's twelve campfire stories (2.8, slice "buiten"): id -> (title, seven lines he tells, the short text in the
verhalenbundel). Lore: guhs are always lief; they're never "te vads", only not vahoeg enough, because the Mika's steal
the kaasknabbels. All Dutch (also in en_us).
"""

VERHALEN = {
    "eerste_kaasknabbel": ("De allereerste kaasknabbel", [
        "Lang, lang geleden, toen mijn opa nog een babyguhtje was, bestonden er nog helemaal geen kaasknabbels.",
        "De guhs aten gras. Gewoon gras. Ze waren lief, maar ze waren nooit, nooit vahoeg. Njeg.",
        "Op een nacht viel er een ster uit de lucht. Hij rolde de heuvel af en bleef liggen in een plasje kaassaus.",
        "De volgende ochtend was die ster knapperig en geel geworden, en hij rook... hmmm... naar kaas.",
        "Het kleinste guhtje nam een hapje. En toen nog een. En toen riep hij: VAHOEG!",
        "Zo werd de allereerste kaasknabbel geboren. Sindsdien zoeken alle guhs de hemel af naar vallende sterren.",
        "En daarom, kleintjes, is een kaasknabbel eigenlijk een stukje sterrenhemel. Welterusten... *gaap*"],
        "Hoe een gevallen ster in de kaassaus de eerste kaasknabbel werd, en het kleinste guhtje als eerste VAHOEG riep."),
    "mika_die_niet_kon_delen": ("De Mika die niet kon delen", [
        "Ken je de Mika's? Ze zijn niet echt gemeen, hoor. Ze hebben alleen nooit geleerd om te delen.",
        "De allereerste Mika vond een zak kaasknabbels. Hij had er genoeg voor wel honderd guhs.",
        "Maar in plaats van te delen, verstopte hij ze. In een grot. Onder een steen. In zijn sokken.",
        "De guhs in het dorp werden stil en een beetje slap. Ze waren niet vahoeg genoeg, en dat maakte ze verdrietig.",
        "Toen gingen de guhs naar de Mika, niet boos, maar met een taart. Een zelfgebakken taart.",
        "De Mika wist niet wat hij zag. Iemand die zomaar iets aan HEM gaf? Hij liep giechelend weg... zonder zijn knabbels.",
        "Sindsdien stelen Mika's nog steeds, njeg. Maar diep vanbinnen willen ze gewoon ook een stukje taart."],
        "Over de allereerste Mika, die al zijn knabbels verstopte, en de guhs die hem een taart brachten in plaats van boos te worden."),
    "groot_vadsfeest": ("Het Grote Vadsfeest van Opa's opa", [
        "Mijn opa's opa organiseerde ooit het allergrootste feest dat de Guhmensie ooit heeft gezien.",
        "Er was een taart zo hoog als een boom, en kaasknabbels in alle kleuren van de regenboog.",
        "Maar net toen het feest begon... pikte een Kruimel-Mika de hele bovenste laag van de taart! Kruimels overal!",
        "Opa's opa werd niet boos. Hij volgde het kruimelspoor, heel rustig, door het hele dorp.",
        "Aan het eind zat de Kruimel-Mika onder een struik, met taart op zijn neus. Hij giechelde van de zenuwen.",
        "Opa's opa gaf hem een kaasknabbel en zei: 'Kom maar mee, er is genoeg voor iedereen.'",
        "En zo kwam er dat jaar één gast meer op het feest. Een beetje kruimelig, maar heel gezellig. Njeg!"],
        "Het feest met de taart zo hoog als een boom, het kruimelspoor, en de Kruimel-Mika die toch nog mee mocht eten."),
    "pluk_niet_vahoeg": ("Pluk, die niet vahoeg genoeg was", [
        "Er was eens een guhtje dat Pluk heette. Pluk was klein en een beetje dun, en dat vond hij niet leuk.",
        "Hoe hard hij ook zocht, elke keer als hij een kaasknabbel vond, pikte een Mika hem weg. Weer niet vahoeg!",
        "De andere guhs zeiden nooit dat hij te dun was, of te vads, of te wat dan ook. Zulke dingen zeggen guhs niet.",
        "In plaats daarvan gingen ze met z'n allen op zoek. Samen. Een grote rij guhs, oortjes omhoog, neuzen omlaag.",
        "En elke knabbel die ze vonden, deelden ze met Pluk. Hap hap hap.",
        "Aan het eind van de week was Pluk rond en vrolijk en helemaal, helemaal VAHOEG.",
        "Onthoud het, kleintjes: een guh is nooit te vads. Soms heeft hij alleen wat hulp nodig om vahoeg te worden."],
        "Over Pluk, wiens knabbels steeds werden gestolen, en de vriendjes die net zo lang zochten tot hij helemaal vahoeg was."),
    "grote_oren": ("Waarom guhs zulke grote oren hebben", [
        "Heb je je ooit afgevraagd waarom guhs zulke grote, ronde oren hebben? Nou, luister goed.",
        "Vroeger hadden guhs piepkleine oortjes. Zo klein dat ze nooit hoorden als er een Mika aan kwam sluipen.",
        "Dus verdwenen er steeds maar kaasknabbels. Niemand hoorde iets. Tip-tip-tip... weg!",
        "Toen besloten de guhs om elke avond, voor het slapengaan, heel goed te luisteren. Naar de wind. Naar de sterren.",
        "En van al dat luisteren werden hun oren groter. En groter. En ronder.",
        "Nu horen guhs een Mika al op honderd stappen afstand. Zelfs als hij op zijn tenen loopt. Zelfs als hij fluistert.",
        "Dus als je oortjes 's nachts een beetje kriebelen... dan groeien ze nog een klein beetje. Sst, luister maar."],
        "Waarom de guhs zulke grote ronde oren kregen: van al het luisteren of er geen Mika aan kwam sluipen."),
    "knabbelberg": ("De Knabbelberg aan het eind van de wereld", [
        "Ver, ver weg, voorbij de laatste guhdorpen, ligt het Guheinde. Daar zweven eilanden in de lucht.",
        "En in het midden staat de Knabbelberg: een berg van alle kaasknabbels die de Mika's ooit hebben gestolen.",
        "Er zijn guhs die zeggen dat hij tot aan de sterren reikt. Anderen zeggen dat hij ruikt naar gefrituurde kaas.",
        "Alleen de dapperste guhs gaan erheen. Niet om te vechten, hoor. Guhs vechten niet.",
        "Ze gaan erheen om de knabbels terug te halen, zodat iedereen thuis weer vahoeg kan worden.",
        "Misschien ga jij er later ook wel eens heen. Neem dan genoeg kaasknabbels mee voor onderweg.",
        "Maar nu nog niet, hoor. Nu eerst lekker slapen. De Knabbelberg loopt niet weg. Njeg."],
        "Over het Guheinde, de zwevende eilanden en de Knabbelberg, waar de Mika's alle gestolen kaasknabbels bewaren."),
    "grote_knabbel": ("Hoe De Grote Knabbel aan de hemel kwam", [
        "Kijk eens omhoog. Zie je die sterren daar, in de vorm van een kaasknabbel? Dat is De Grote Knabbel.",
        "Heel lang geleden was er een guh die zo veel van kaasknabbels hield, dat hij ze aan iedereen wilde laten zien.",
        "Dus klom hij op de hoogste berg, met de allermooiste knabbel die hij had.",
        "Hij hield hem zo hoog als hij kon en riep: KIJK! VAHOEG!",
        "De maan vond hem zo mooi, dat ze hem voorzichtig oppakte en tussen de sterren legde.",
        "Nu kan iedere guh hem zien, elke nacht. Professor Sterretje zegt dat hij er nog steeds een beetje naar ruikt.",
        "Als je hem ooit door een telescoop vindt, doe dan een wens. Hij luistert altijd."],
        "De guh die zijn mooiste kaasknabbel aan de maan liet zien, zodat hij nu voor altijd tussen de sterren staat."),
    "wolkjes_eerste_vlucht": ("Kapitein Wolkjes allereerste vlucht", [
        "Kapitein Wolkje was vroeger helemaal geen kapitein. Hij was gewoon Wolkje, een guhtje dat graag naar wolken keek.",
        "Hij wilde zo graag vliegen. Hij probeerde het met een paraplu. Plof. Met een laken. Plof. Met zijn oren. Dubbel plof.",
        "Toen zag hij een zeepbel wegzweven, en hij dacht: warme lucht gaat omhoog!",
        "Hij naaide een ballon van oude guhsokken, in de vorm van zijn eigen hoofd. Met oortjes en al.",
        "De eerste keer ging hij één blok omhoog. De tweede keer twee. De derde keer... tot boven de wolken!",
        "Van daarboven zag hij de hele Guhmensie, en hij huilde een beetje, omdat het zo mooi was.",
        "Sindsdien neemt hij iedereen mee die dat ook wil zien. Morgen misschien jou, njeg!"],
        "Hoe Wolkje met een ballon van oude guhsokken voor het eerst tot boven de wolken vloog, en Kapitein Wolkje werd."),
    "kaasregen": ("De dag dat het kaasknabbels regende", [
        "Het gebeurt niet vaak, maar soms... soms regent het kaasknabbels. Echt waar!",
        "De eerste keer dat het gebeurde, wist niemand wat er aan de hand was. Tik, tik, tik, op alle daken.",
        "De guhs renden naar buiten met hun mond open. Hap! Hap! Hap!",
        "Zelfs de Mika's kwamen kijken. Ze vergaten helemaal om te stelen, zo blij waren ze.",
        "Die dag was iedereen tegelijk vahoeg. Guhs, Mika's, zelfs de bijtjes.",
        "Het was de gezelligste dag die de Guhmensie ooit heeft gekend.",
        "Dus als je ooit een kaasregen ziet: ren naar buiten, doe je mond open, en deel met wie er naast je staat."],
        "De eerste kaasregen, toen alle guhs met hun mond open naar buiten renden en zelfs de Mika's vergaten te stelen."),
    "verdwaalde_babyguh": ("De verdwaalde babyguh", [
        "Er was eens een babyguhtje dat achter een vlinder aan liep. Heel ver. Veel te ver.",
        "Toen hij omkeek, was zijn familie weg. Alleen maar bomen. Hoge, donkere reuzenguhbomen.",
        "Hij ging op een steen zitten en zijn oortjes hingen omlaag. Hij voelde zich helemaal niet vahoeg.",
        "Maar weet je wat hij toen deed? Hij zong. Een heel zacht guhliedje. Guh, guh, guh.",
        "En ver weg, heel ver weg, hoorde zijn mama dat liedje, met haar grote ronde oren.",
        "Ze vond hem, knuffelde hem, en samen kropen ze die nacht in een warm guhnestje.",
        "Dus als je ooit verdwaalt, kleintje: zing maar. Er luistert altijd wel een guh."],
        "Over het babyguhtje dat verdwaalde in het bos en door te zingen zijn mama weer terugvond."),
    "mika_met_gouden_hart": ("De Mika met het gouden hart", [
        "Niet alle Mika's blijven altijd stelen. Dit is het verhaal van Mika Goudhart.",
        "Hij was de beste knabbeldief van allemaal. Hij stal zelfs de knabbels uit de zakken van andere Mika's.",
        "Op een avond zag hij een guhtje huilen, omdat al zijn knabbels weg waren. Door hem.",
        "Mika Goudhart kreeg een raar gevoel in zijn buik. Geen honger. Iets anders.",
        "Die nacht sloop hij terug, en legde alle knabbels weer voor de deur. Met nog een paar extra.",
        "De volgende ochtend was het guhtje zo vahoeg, dat het de hele dag huppelde. En Mika keek stiekem toe en glimlachte.",
        "Misschien heeft elke Mika wel een klein gouden hartje. Je moet het alleen even laten glimmen. Welterusten."],
        "Over de beste knabbeldief van alle Mika's, die op een nacht alles teruggaf, en nog een paar extra."),
    "knuffeldal": ("Hoe het Knuffeldal ontstond", [
        "Dit is mijn allerlievelingsverhaal. Het gaat over deze plek, hier. Het Knuffeldal.",
        "Heel vroeger was dit een koude, kale vallei. Er groeide niks, er woonde niemand.",
        "Toen kwam er een oude guh langs, heel moe van het zoeken naar kaasknabbels. Hij ging liggen en viel in slaap.",
        "Hij droomde van een plek waar het altijd zacht en roze was, waar iedereen elkaar knuffelde, en niemand ooit alleen was.",
        "En omdat guhdromen soms uitkomen, groeide er de volgende ochtend overal zacht roze gras. En pluizenbomen. En guhs.",
        "Ze bouwden een stadje, met een plein en een fontein, en elk jaar vieren ze het Grote Knusfeest.",
        "Wie die oude guh was? Hmm... misschien was het wel mijn opa. Of misschien... was ik het zelf. Welterusten, kleintjes. *snurk*"],
        "Opa Guhs allerlievelingsverhaal: hoe een koude kale vallei uit een guhdroom veranderde in het zachte roze Knuffeldal."),
}
