"""
Het Knuffeldal (2.8) - every text of the knuffeldal feature and the shared Knus framework (Dutch everywhere, also in
en_us, with plenty of njeg, vads and VAHOEG). Cocotje's lines are the user's own words: keep them exactly as they are.
"""
SEIZOENEN = {"lente": "Lente", "zomer": "Zomer", "herfst": "Herfst", "winter": "Winter"}
TAKEN = {"feesttaart": "Feesttaart", "theeservies": "Theeservies", "feestkapsels": "Feestkapsels", "feestslingers": "Feestslingers",
         "feestbloemen": "Feestbloemen", "sterrenlantaarns": "Sterrenlantaarns"}
TAAK_WAAR = {
    "feesttaart": "Bakker Korstje bakt hem in de Knabbelbakkerij, aan de noordkant van het plein.",
    "theeservies": "Mevrouw Theelepel leent het uit na een gezellig theekransje in het Knabbelthee-huisje (oostkant).",
    "feestkapsels": "Kapper Krulletje knipt ze tijdens een feestelijke kappersshow in Knip & Vads (zuidkant).",
    "feestslingers": "De babyguhtjes van Juf Knuffel knutselen ze in de Knuffelcreche (westkant).",
    "feestbloemen": "Kweek guhbloemetjes in je eigen tuintje en maak er een feestboeket van.",
    "sterrenlantaarns": "Professor Sterretje geeft ze als je een sterrenbeeld verbindt in de Guh-Sterrenwacht.",
}
BEWONERS = {
    "pluisje": ("Pluisje", ["Hoi! Ik ben Pluisje. Mijn huis heeft de pluizigste oren van het hele Knuffeldal. VAHOEG!",
                            "Weet je wat ik het liefst doe? In een bladerhoopje springen. Wiiieee! Maar dat kan alleen in de herfst, njeg.",
                            "Mijn vacht is zo pluizig, ik verlies soms een pluisje. Zie je ze zweven? Dat zijn er van mij."]),
    "knabbeltje": ("Knabbeltje", ["Ik ben Knabbeltje en ik ruik kaasknabbels van héél ver. Heb je er toevallig eentje bij je? Njeg?",
                                  "Mijn dak is geel, net als een kaasknabbel. Dan word ik 's ochtends al vads wakker.",
                                  "Die Kruimel-Mika's pikken soms onze knabbels, njeg! Dan worden we niet vahoeg genoeg."]),
    "dikkie": ("Dikkie", ["Hallo, ik ben Dikkie. Ik ben niet te vads hoor. Je kunt nooit te vads zijn! Alleen niet vahoeg genoeg.",
                          "Op het feestbuffet ben ik altijd als eerste. En als laatste. VAHOEG!",
                          "Ik heb een zitzak boven in mijn huis. Daar zak ik zo lekker vadsig in weg..."]),
    "mollie": ("Mollie", ["Hoi hoi, ik ben Mollie! Ik ben een beetje verlegen... maar jij mag best even blijven.",
                          "Zullen we samen naar de fontein kijken? Die grote guhkop spuugt water, hihi.",
                          "In de lente vlecht ik bloesemkransjes bij de bloembakken. Probeer het ook eens, met drie bloemetjes!"]),
    "sproetje": ("Sproetje", ["Ik ben Sproetje, de kleinste van het dal! Maar mijn oren zijn ENORM. Njeg.",
                              "Opa Guh vertelt 's avonds verhalen bij het kampvuur. Over Mika's en kaasknabbels. Spannend!",
                              "Ik ga later burgemeester worden. Of bakker. Of allebei! VAHOEG!"]),
    "bolletje": ("Bolletje", ["Ik ben Bolletje, ik woon naast de speeltuin. Glijbaan! Schommel! Klimkoepel! VAHOEG!",
                              "In de winter bouw ik sneeuwpopguhs: twee sneeuwblokken, een sneeuwguhkopje erop, klaar!",
                              "Soms word ik zo moe van het spelen dat ik gewoon in het zand in slaap val. Zzz... njeg."]),
}

LANG = {
    # --- the Knus framework: the Guhdex's Knus tab ---
    "gui.guhs.guhdex.tab.guhs": "Guhs",
    "gui.guhs.guhdex.tab.knus": "Knus",
    "gui.guhs.knus.terug": "< Terug",
    "gui.guhs.knus.binnenkort": "binnenkort",
    "gui.guhs.knus.binnenkort_lang": "Hier komt binnenkort nog meer knus! Njeg, nog even geduld...",
    "gui.guhs.knus.kies": "Klik op een onderdeel voor zijn mijlpalen en verzamelingen",
    "gui.guhs.knus.mijlpalen": "Mijlpalen",
    "gui.guhs.knus.verzamelingen": "Verzamelingen",
    "gui.guhs.knus.klik_item": "Klik op een plaatje (of beweeg erover) om te lezen wat het is.",
    "gui.guhs.knus.nog_niet": "??? Nog niet ontdekt. Njeg, zoek nog maar even!",
    "gui.guhs.knus.nieuw_item": "Nieuw in je Guhdex: %s (%s, %s/%s)",
    "gui.guhs.knus.mijlpaal_bereikt": "Knus-mijlpaal: %s! Haal je beloning op in je Guhdex (tab Knus). VAHOEG!",
    "gui.guhs.knus.toast.mijlpaal": "Knus-mijlpaal!",
    "quest.guhs.knus.binnenkort": "Njeg, ik ben nog niet helemaal klaar! Kom binnenkort terug, dan heb ik iets heel knus voor je. Vahoeg!",
    # the sections
    "gui.guhs.knus.onderdeel.knuffeldal": "Het Knuffeldal",
    "gui.guhs.knus.onderdeel.seizoenen": "Seizoenen",
    "gui.guhs.knus.onderdeel.bakkerij": "Knabbelbakkerij",
    "gui.guhs.knus.onderdeel.creche": "Knuffelcreche",
    "gui.guhs.knus.onderdeel.theehuis": "Knabbelthee-huisje",
    "gui.guhs.knus.onderdeel.kapper": "Knip & Vads",
    "gui.guhs.knus.onderdeel.boerderij": "Guhboerderij",
    "gui.guhs.knus.onderdeel.tuintjes": "Guhtuintjes",
    "gui.guhs.knus.onderdeel.sterrenwacht": "Guh-Sterrenwacht",
    "gui.guhs.knus.onderdeel.ballon": "Ballonfestival",
    "gui.guhs.knus.onderdeel.kamperen": "Kampeerplekjes",
    "gui.guhs.knus.onderdeel.knuffelbad": "Knuffelbad",
    "gui.guhs.knus.onderdeel.wereldleven": "Guhleven",
    # the milestones of the knuffeldal feature
    "gui.guhs.knus.mijlpaal.knuffeldal_gevonden": "Welkom in het Knuffeldal",
    "gui.guhs.knus.mijlpaal.knuffeldal_vriendjes": "Alle buren leren kennen (6)",
    "gui.guhs.knus.mijlpaal.knuffeldal_cocotje": "Cocotje geholpen",
    "gui.guhs.knus.mijlpaal.knuffeldal_knusfeest": "Het Grote Knusfeest begint",
    "gui.guhs.knus.mijlpaal.knuffeldal_taakjes": "Zes feesttaakjes gebracht",
    "gui.guhs.knus.mijlpaal.knuffeldal_kruimelmikas": "Drie Kruimel-Mika's weggelokt",
    "gui.guhs.knus.mijlpaal.knuffeldal_finale": "Knuffelburgemeester!",
    "gui.guhs.knus.mijlpaal.knuffeldal_seizoensfeesten": "Vier seizoensfeesten gevierd",
    "gui.guhs.knus.mijlpaal.knuffeldal_pluisguh": "Een Pluisguh getemd",
    "gui.guhs.knus.mijlpaal.seizoenen_lente": "De lente in het plakboek",
    "gui.guhs.knus.mijlpaal.seizoenen_zomer": "De zomer in het plakboek",
    "gui.guhs.knus.mijlpaal.seizoenen_herfst": "De herfst in het plakboek",
    "gui.guhs.knus.mijlpaal.seizoenen_winter": "De winter in het plakboek",
    "gui.guhs.knus.mijlpaal.seizoenen_alle": "Alle vier de seizoenen",
    "gui.guhs.knus.mijlpaal.seizoenen_bladerhoopjes": "Tien keer in een bladerhoopje gesprongen",
    # the collections
    "gui.guhs.knus.verzameling.knuffelvriendjes": "Knuffelvriendjes",
    "gui.guhs.knus.verzameling.seizoensplakboek": "Seizoensplakboek",
    "gui.guhs.knus.knuffelvriendjes.burgemeester": "Burgemeester Vadsema",
    "gui.guhs.knus.knuffelvriendjes.burgemeester.info": "De burgemeester van het Knuffeldal. Hij houdt van feestjes, lijstjes en zijn ambtsketen. Vooral van feestjes.",
    "gui.guhs.knus.knuffelvriendjes.cocotje": "Cocotje",
    "gui.guhs.knus.knuffelvriendjes.cocotje.info": "OHJA ZE HANGEN AAN ME VEH. Omda je vahoeg beh. Njeg.",
    "gui.guhs.knus.knuffelvriendjes.opa_guh": "Opa Guh",
    "gui.guhs.knus.knuffelvriendjes.opa_guh.info": "Zit op zijn bankje bij het kampvuur en weet alles van vroeger. Van héél vroeger.",
    "gui.guhs.knus.seizoensplakboek.lente_kransje": "Een bloesemkransje gevlochten",
    "gui.guhs.knus.seizoensplakboek.lente_kransje.info": "In de lente bloeien de seizoensbloembakken. Drie bloemetjes erop: een bloesemkransje!",
    "gui.guhs.knus.seizoensplakboek.lente_guh": "Een guh met een bloesemkransje",
    "gui.guhs.knus.seizoensplakboek.lente_guh.info": "Je tamme guh droeg een bloesemkransje in de lente. Zo lief, VAHOEG!",
    "gui.guhs.knus.seizoensplakboek.zomer_hoedje": "Een zonnehoedje gevlochten",
    "gui.guhs.knus.seizoensplakboek.zomer_hoedje.info": "In de zomer staan de bloembakken vol zonnebloemen. Drie tarwe erop: een strooien zonnehoedje!",
    "gui.guhs.knus.seizoensplakboek.zomer_guh": "Een guh met een zonnehoedje",
    "gui.guhs.knus.seizoensplakboek.zomer_guh.info": "Je tamme guh hield zijn snoet uit de zon met een zonnehoedje. Heerlijk vads.",
    "gui.guhs.knus.seizoensplakboek.herfst_hoopje": "In een bladerhoopje gesprongen",
    "gui.guhs.knus.seizoensplakboek.herfst_hoopje.info": "In de herfst worden de bladerhoopjes groot en zacht. Spring erin van een stukje hoogte: wiiieee!",
    "gui.guhs.knus.seizoensplakboek.herfst_guh": "Samen met je guh in de blaadjes",
    "gui.guhs.knus.seizoensplakboek.herfst_guh.info": "Je tamme guh sprong met je mee in het bladerhoopje en rolde er lekker doorheen.",
    "gui.guhs.knus.seizoensplakboek.winter_sneeuwpop": "Een sneeuwpopguh gebouwd",
    "gui.guhs.knus.seizoensplakboek.winter_sneeuwpop.info": "Twee sneeuwblokken op elkaar, een sneeuwguhkopje erop: een sneeuwpopguh! (In de winter telt hij.)",
    "gui.guhs.knus.seizoensplakboek.winter_guh": "Een guh met een sjaaltje",
    "gui.guhs.knus.seizoensplakboek.winter_guh.info": "Je tamme guh droeg in de winter een knus sjaaltje. Warm en vahoeg.",
    # --- seasons and parts of the day ---
    "gui.guhs.seizoen.nu": "Het is %s in de Guhmensie (dag %s van %s).",
    "gui.guhs.seizoen.gezet": "Het is nu %s!",
    "gui.guhs.seizoen.meer_nodig": "Njeg, daar heb je er %s van nodig: %s",
    "gui.guhs.seizoen.gemaakt": "VAHOEG! Je hebt een %s gemaakt!",
    "gui.guhs.seizoen.sneeuwpop": "Een sneeuwpopguh! Hij kijkt je heel vrolijk aan.",
    "gui.guhs.seizoen.tip.lente": "Lente! Leg drie bloemetjes op de bloembak voor een bloesemkransje.",
    "gui.guhs.seizoen.tip.zomer": "Zomer! Leg drie tarwe op de bloembak voor een strooien zonnehoedje.",
    "gui.guhs.seizoen.tip.herfst": "Herfst! Spring in de bladerhoopjes. Vier bladeren op de bloembak: bladerhoopjes voor thuis.",
    "gui.guhs.seizoen.tip.winter": "Winter! Drie wol: een knus sjaaltje. Drie sneeuwballen: een sneeuwguhkopje.",
    "gui.guhs.dagdeel.ochtend": "Ochtend", "gui.guhs.dagdeel.dag": "Dag", "gui.guhs.dagdeel.dutje": "Middagdutje",
    "gui.guhs.dagdeel.avond": "Avond", "gui.guhs.dagdeel.nacht": "Nacht",
    # --- the Knusfeest ---
    "gui.guhs.knusfeest.stap.gevraagd": "nog doen",
    "gui.guhs.knusfeest.stap.gemaakt": "klaar, breng het naar de burgemeester!",
    "gui.guhs.knusfeest.stap.gestolen": "gestolen door een Kruimel-Mika! Volg de kruimels...",
    "gui.guhs.knusfeest.stap.teruggevonden": "teruggevonden, breng het snel!",
    "gui.guhs.knusfeest.stap.gebracht": "gebracht, VAHOEG!",
    "gui.guhs.knusfeest.lijst_kop": "Het Grote Knusfeest - feesttaakjes:",
    "gui.guhs.knusfeest.lijst_kop_seizoen": "Het seizoensfeest - feesttaakjes:",
    "gui.guhs.knusfeest.lijst_klaar": "Er zijn nu geen feesttaakjes. Kom volgend seizoen terug bij Burgemeester Vadsema!",
    "gui.guhs.knusfeest.lijst_leeg": "Het lijstje is nog leeg. Praat eerst met Burgemeester Vadsema op het plein van het Knuffeldal.",
    "gui.guhs.knusfeest.hint": "! = heb je bij je, ? = gestolen: volg de kruimels",
    # --- Burgemeester Vadsema ---
    "quest.guhs.burgemeester.start": "Ahum! Welkom, welkom in het Knuffeldal! Ik ben Burgemeester Vadsema. Straks is het Grote Knusfeest... en er is NIETS klaar! Geen taart, geen thee, geen slingers, njeg! Wil jij helpen? Hier is mijn lijstje met zes feesttaakjes. En pas op voor de Kruimel-Mika's: die pikken alles!",
    "quest.guhs.burgemeester.lijst": "Kijk, dit staat er nog op het lijstje. Breng alles hier, dan tik ik het af. Ahum, VAHOEG!",
    "quest.guhs.burgemeester.hoi": "Ah, daar ben je weer! Hoe gaat het met de feesttaakjes? Laat eens zien wat je bij je hebt.",
    "quest.guhs.burgemeester.hoi_collega": "Ahum! Collega Knuffelburgemeester! Wat fijn. Hoe gaat het met de feesttaakjes?",
    "quest.guhs.burgemeester.dank": "Oh, VAHOEG! Dank je wel! Weer een feesttaakje van het lijstje. Het Knusfeest wordt zo knus!",
    "quest.guhs.burgemeester.niets": "Njeg, je hebt nog niks voor het feest bij je. Kijk maar op het lijstje wat er nog moet.",
    "quest.guhs.burgemeester.alles": "Alles is er! De taart, de thee, de kapsels, de slingers, de bloemen en de lantaarns! Dan... is het nu tijd voor... HET GROTE KNUSFEEST! Naar het feestbuffet, allemaal! Neem je guhs mee!",
    "quest.guhs.burgemeester.alles_seizoen": "Alles is er! Dan vieren we nu het seizoensfeest. Aan het buffet, iedereen! VAHOEG!",
    "quest.guhs.burgemeester.klaar.0": "Wat een feest was dat. Mijn buikje is nog steeds vol. Kom volgend seizoen terug, dan vieren we het weer!",
    "quest.guhs.burgemeester.klaar.1": "Ahum. Als burgemeester moet ik zeggen: dit is het knusste dal van de hele Guhmensie. Dankzij jou!",
    "quest.guhs.burgemeester.klaar.2": "Heb je Opa Guh al eens gehoord bij het kampvuur? Hij vertelt de allermooiste verhalen. Soms valt hij halverwege in slaap, njeg.",
    "quest.guhs.burgemeester.seizoen.lente": "Het is lente! Tijd voor het lentefeest! Ik heb een paar nieuwe feesttaakjes op mijn lijstje gezet. Help je weer?",
    "quest.guhs.burgemeester.seizoen.zomer": "Het is zomer! Het zomerfeest komt eraan, en ik heb weer een lijstje. Zonnehoedjes op en aan de slag, VAHOEG!",
    "quest.guhs.burgemeester.seizoen.herfst": "Het is herfst! Voor het herfstfeest heb ik een paar feesttaakjes. Tussendoor even in de bladerhoopjes springen mag!",
    "quest.guhs.burgemeester.seizoen.winter": "Het is winter! Het winterfeest wordt het knusste feest van het jaar. Help je met mijn lijstje?",
    "quest.guhs.burgemeester.teruggevonden": "Ahum! Ik heb je %s teruggevonden bij de fontein. Die Kruimel-Mika heeft hem daar laten liggen. Afgetikt!",
    "quest.guhs.burgemeester.optie.geven": "Geven!",
    # --- Cocotje (the user's own words: keep them exactly) ---
    "quest.guhs.cocotje.vraag": "WEET JIJ WAAR ZE ZIJN??????",
    "quest.guhs.cocotje.optie.1": "Ik ga gelijk zoeken!",
    "quest.guhs.cocotje.optie.2": "Ik zie ze aan je hangen Cocotje",
    "quest.guhs.cocotje.optie.3": "Wie is ze?",
    "quest.guhs.cocotje.optie.4": "omda je vahoeg beh",
    "quest.guhs.cocotje.antwoord.1": "Njeg succes. Ik vads het nog wel als je iets weet",
    "quest.guhs.cocotje.antwoord.2": "OHJA ZE HANGEN AAN ME VEH",
    "quest.guhs.cocotje.antwoord.3": "hmmm da wik dus ook ekkes nie eigi...",
    "quest.guhs.cocotje.antwoord.4": "njeg.",
    "quest.guhs.cocotje.lief.0": "njeg.",
    "quest.guhs.cocotje.lief.1": "ze hangen nog steeds aan me veh. njeg.",
    "quest.guhs.cocotje.lief.2": "*zwaait met haar oren* vahoeg he",
    "quest.guhs.cocotje.lief.3": "*knuffelt je* njeg.",
    # --- the residents ---
    "quest.guhs.knuffeldal.bewoner.hoi": "Hoi! Welkom in het Knuffeldal. VAHOEG!",
    "quest.guhs.knuffeldal.bewoner.knabbel": "Mjam, een kaasknabbel! Dank je wel! Maar mee kan ik niet hoor, ik woon hier. Njeg.",
    # --- the town, the feast, the Kruimel-Mika's ---
    "gui.guhs.knuffeldal.beschermd": "Njeg! Het Knuffeldal is zo knus, daar mag niks aan veranderen.",
    "gui.guhs.knuffeldal.welkom": "Welkom in het Knuffeldal! Burgemeester Vadsema staat op zijn bordes op het plein. VAHOEG!",
    "gui.guhs.knuffeldal.praat": "Praten",
    "gui.guhs.knuffeldal.doei": "Doei!",
    "gui.guhs.knuffeldal.titel": "Knuffelburgemeester",
    "gui.guhs.knuffeldal.titel_gekregen": "%s is nu Knuffelburgemeester van het Knuffeldal! VAHOEG!",
    "gui.guhs.knuffeldal.oorkonde": "Voor de Knuffelburgemeester, met dank van het hele Knuffeldal. VAHOEG!",
    "gui.guhs.knuffeldal.seizoensfeest_klaar": "Wat een knus seizoensfeest! Burgemeester Vadsema zwaait je uit. Tot volgend seizoen!",
    "gui.guhs.knuffeldal.buffet.gedekt": "Het buffet is gedekt! Leg er iets lekkers op: gebak, oogst, thee, kaasmelk of kaasknabbels.",
    "gui.guhs.knuffeldal.buffet.leeg": "Een feestbuffettafel. Tijdens een Knusfeest staat hij vol lekkers!",
    "gui.guhs.knuffeldal.buffet.zelfgemaakt": "Zelfgemaakt! %s staat nu op het buffet. De guhs kijken er vadsig naar.",
    "gui.guhs.knuffeldal.buffet.erop": "%s staat nu op het buffet. Mjam!",
    "gui.guhs.knuffeldal.feest.groot": "HET GROTE KNUSFEEST! Alle guhs komen naar het feestbuffet. Leg er zelf ook wat lekkers op!",
    "gui.guhs.knuffeldal.feest.seizoen": "Het seizoensfeest begint! De guhs komen smullen aan het feestbuffet.",
    "gui.guhs.knuffeldal.feest.einde": "Het feest is voorbij. Iedereen is vol, vadsig en heel erg vahoeg.",
    "gui.guhs.kruimel_mika.gestolen": "*giechel* Een Kruimel-Mika graait je %s weg en rent ervandoor! Volg de kruimels...",
    "gui.guhs.kruimel_mika.gelokt": "De Kruimel-Mika snuffelt aan je lekkernij... hij vergeet zijn buit! Geef hem de lekkernij (rechtsklik).",
    "gui.guhs.kruimel_mika.zonder": "*giechel* Zonder lekkernij krijg je hem niet terug, njeg! (kaasknabbels of gebak)",
    "gui.guhs.kruimel_mika.terug": "De Kruimel-Mika smult van je lekkernij en laat je %s los! Hij rent giechelend weg.",
    "gui.guhs.kruimel_mika.niet_meppen": "Njeg, niet meppen! Kruimel-Mika's lok je weg met een lekkernij.",
    "gui.guhs.evenement.knusfeest": "Knusfeest",
    "gui.guhs.evenement.start.knusfeest": "Het Knusfeest! Iedereen naar het feestbuffet, met al je guhs!",
    # --- the superkompas ---
    "gui.guhs.superkompas.knus": "Knus",
    "gui.guhs.superkompas.knus.tooltip": "Knusse plekjes: het Knuffeldal, de boerderij, de sterrenwacht, het ballonfestival...",
    "gui.guhs.superkompas.category.knus": "Knus",
    "structure.guhs.knuffeldal_stadje": "Knuffeldal",
    "structure.guhs.knuffeldal_stadje.tooltip": "Het knusse stadje in het midden van het Knuffeldal: Burgemeester Vadsema, het Grote Knusfeest, Cocotje...",
    # --- the Highscores rows of 2.8 (the games themselves are in the phase-2 features) ---
    "gui.guhs.highscores.game.bakkerij": "Knabbelbakkerij",
    "gui.guhs.highscores.game.creche": "Babyguhtjes terugbrengen",
    "gui.guhs.highscores.game.kapper": "Kappersshow",
    "gui.guhs.highscores.game.glijbaan_roze_trechter": "Roze Trechter",
    "gui.guhs.highscores.game.glijbaan_glimtunnel": "Glimtunnel",
    "gui.guhs.highscores.game.glijbaan_grote_plons": "Grote Plons",
    # --- names ---
    "biome.guhs.knuffeldal": "Knuffeldal",
    "block.guhs.knuffelgras": "Knuffelgras", "block.guhs.pluisgras": "Pluisgras", "block.guhs.pluizenboom_stam": "Pluizenboomstam",
    "block.guhs.pluizenboom_bladeren": "Pluizenboombladeren", "block.guhs.pluizenboom_zaailing": "Pluizenboomzaailing",
    "block.guhs.guhpaddenstoel": "Guhpaddenstoeltje", "block.guhs.guhpaddenstoel_hoed": "Guhpaddenstoelhoed",
    "block.guhs.guhpaddenstoel_steel": "Guhpaddenstoelsteel",
    "block.guhs.knuffelsteen": "Knuffelsteen", "block.guhs.knuffelsteen_trap": "Knuffelsteentrap", "block.guhs.knuffelsteen_plaat": "Knuffelsteenplaat",
    "block.guhs.knuffelsteen_muur": "Knuffelsteenmuurtje", "block.guhs.knuffelsteen_gezicht": "Guhgezichtje in knuffelsteen",
    "block.guhs.pluisdak": "Pluisdak", "block.guhs.pluisdak_trap": "Pluisdaktrap", "block.guhs.pluisdak_plaat": "Pluisdakplaat",
    "block.guhs.knuffelklinkers": "Knuffelklinkers",
    "block.guhs.feestbuffettafel": "Feestbuffettafel", "block.guhs.knus_oorkonde": "Knus-oorkonde",
    "block.guhs.seizoensbloembak": "Seizoensbloembak", "block.guhs.seizoensslinger": "Seizoensslinger",
    "block.guhs.bladerhoopje": "Bladerhoopje", "block.guhs.sneeuwpopguh": "Sneeuwpopguh",
    "item.guhs.knusfeestlijstje": "Knusfeestlijstje", "item.guhs.sneeuwguhkopje": "Sneeuwguhkopje",
    "item.guhs.kruimel_mika_spawn_egg": "Kruimel-Mika-spawnei",
    "item.guhs.burgemeesterssjerp": "Burgemeesterssjerp", "item.guhs.bloesemkransje": "Bloesemkransje",
    "item.guhs.zonnehoedje": "Zonnehoedje", "item.guhs.knus_sjaaltje": "Knus sjaaltje",
    # lore
    "block.guhs.pluisgras.lore": "Zacht roze pluis. Er zweeft af en toe een pluisje af.",
    "block.guhs.pluizenboom_zaailing.lore": "Groeit uit tot een pluizige roze boom",
    "block.guhs.guhpaddenstoel.lore": "Beendermeel erop: een reuzenguhpaddenstoel!",
    "block.guhs.knuffelsteen_gezicht.lore": "Rechtsklik: een ander gezichtje",
    "block.guhs.feestbuffettafel.lore": "Tijdens een Knusfeest staat hij vol lekkers",
    "block.guhs.seizoensbloembak.lore": "Bloeit mee met de seizoenen. Rechtsklik: wat kun je er nu mee?",
    "block.guhs.bladerhoopje.lore": "In de herfst: spring erin!",
    "block.guhs.sneeuwpopguh.lore": "Brrr, maar wel vahoeg",
    "block.guhs.knus_oorkonde.lore": "Voor de Knuffelburgemeester van het Knuffeldal",
    "item.guhs.knusfeestlijstje.lore": "Rechtsklik: welke feesttaakjes staan er nog open?",
    "item.guhs.sneeuwguhkopje.lore": "Zet me op twee sneeuwblokken!",
    "item.guhs.sneeuwguhkopje.hoe": "Zet het sneeuwguhkopje bovenop twee sneeuwblokken, dan heb je een sneeuwpopguh!",
    # creatures and characters
    "entity.guhs.kruimel_mika": "Kruimel-Mika",
    "entity.guhs.guh.pluisguh": "Pluisguh",
    "entity.guhs.guh_npc.burgemeesterguh": "Burgemeester Vadsema",
    "entity.guhs.guh_npc.cocotje": "Cocotje",
    "gui.guhs.guhdex.rarity.pluisguh": "Zeldzaamheid: Ongewoon (alleen in het Knuffeldal)",
    "gui.guhs.guhdex.info.pluisguh": "Een extra pluizige roze guh met een pluizig kuifje en pluizige wangetjes. Woont alleen in het Knuffeldal en wil maar al te graag geknuffeld worden. Tem hem met kaasknabbels!",
    "gui.guhs.guhdex.rarity.burgemeesterguh": "Zeldzaamheid: Uniek (op het plein van het Knuffeldal)",
    "gui.guhs.guhdex.info.burgemeesterguh": "Burgemeester Vadsema, met hoge hoed en gouden ambtsketen. Organiseert het Grote Knusfeest en daarna elk seizoen een seizoensfeest. Ahum!",
    "gui.guhs.guhdex.rarity.kruimel_mika": "Zeldzaamheid: Stiekem (alleen als ze iets pikken)",
    "gui.guhs.guhdex.info.kruimel_mika": "Een kleine Mika vol koekkruimels. Vecht nooit, pikt alleen: feesttaarten, theeserviezen, slingers... Lok hem weg met een lekkernij, dan rent hij giechelend weg.",
    "gui.guhs.guhdex.rarity.cocotje": "Zeldzaamheid: Uniek (in haar huisje in het Knuffeldal)",
    "gui.guhs.guhdex.info.cocotje": "Cocotje is altijd iets kwijt. Ze hangen aan haar veh. Njeg.",
    "entity.guhs.guh_npc.opa_guh": "Opa Guh",
    # sounds
    "subtitles.guhs.knuffeldal.kruimel_giechel": "Kruimel-Mika giechelt",
    "subtitles.guhs.knuffeldal.feestbel": "Feestbel klingelt",
    "subtitles.guhs.knuffeldal.seizoen": "Het seizoen wisselt",
}
for sid, naam in SEIZOENEN.items():
    LANG[f"gui.guhs.seizoen.{sid}"] = naam
LANG["gui.guhs.seizoen.wissel.lente"] = "De Guhmensie bloeit: het is LENTE! De bloembakken in het Knuffeldal staan vol bloesem. VAHOEG!"
LANG["gui.guhs.seizoen.wissel.zomer"] = "De zon schijnt vadsig: het is ZOMER! Tijd voor zonnehoedjes in het Knuffeldal."
LANG["gui.guhs.seizoen.wissel.herfst"] = "De blaadjes vallen: het is HERFST! De bladerhoopjes in het Knuffeldal zijn weer groot. Spring erin!"
LANG["gui.guhs.seizoen.wissel.winter"] = "Brrr, het is WINTER! Sjaaltjes om en sneeuwpopguhs bouwen. Njeg, wat koud!"
for tid, naam in TAKEN.items():
    LANG[f"gui.guhs.knusfeest.taak.{tid}"] = naam
    LANG[f"gui.guhs.knusfeest.waar.{tid}"] = TAAK_WAAR[tid]
for bid, (naam, regels) in BEWONERS.items():
    LANG[f"entity.guhs.bewoner.{bid}"] = naam
    LANG[f"gui.guhs.knus.knuffelvriendjes.{bid}"] = naam
    LANG[f"gui.guhs.knus.knuffelvriendjes.{bid}.info"] = regels[0]
    for i, regel in enumerate(regels):
        LANG[f"quest.guhs.knuffeldal.bewoner.{bid}.{i}"] = regel

# the Knuffeldal advancement tab
ADVANCEMENTS = {
    "root": ("Het Knuffeldal", "Knus, lief en guhig: stap de Guhmensie in"),
    "bezocht": ("Zo zacht!", "Loop over het roze knuffelgras van het Knuffeldal"),
    "stadje": ("Welkom in het stadje", "Vind het stadje in het midden van het Knuffeldal"),
    "burgemeester": ("Ahum!", "Praat met Burgemeester Vadsema op zijn bordes"),
    "kruimel_mika_verjaagd": ("Kruimeldief!", "Lok een Kruimel-Mika weg van zijn buit met een lekkernij"),
    "knusfeest_klaar": ("Het Grote Knusfeest", "Breng alle zes feesttaakjes en vier het feest aan het feestbuffet"),
    "knuffelburgemeester": ("Knuffelburgemeester", "Word Knuffelburgemeester van het Knuffeldal. VAHOEG!"),
    "pluisguh_getemd": ("Superpluizig", "Tem een Pluisguh in het Knuffeldal"),
    "seizoen_alle": ("Het hele jaar knus", "Vul het seizoensplakboek: twee dingen in elk seizoen"),
    "cocotje": ("Ze hangen aan haar veh", "Help Cocotje vinden wat ze kwijt is"),
}
